### ISSUE TITLE
No project structure in place

### ISSUE THREAD

**Issue by serefarikan** [ethercis/ethercis#1]
I can't see any project structure for the Java code. Morever, I'm not sure if this code would compile even if there was a project structure in place. 
The import in DayPlanner.java: 

import com.ethercis.ehrserver.definitions.x10.WeekPlan;

is referring to WeekPlan in a namespace which does not exist in any of the repositories. 

Are these repositories supposed to compile? Any chance of an update based on the original development environment?

**Comment by ethercis** [comment]
The code base has been re-structured and committed today. It is split in two parts (ehrservice and VirtualEhr) depending on what is your objective. You can create a simple standalone application with ehrservice bundling it with a GUI. ehrservice contains the components for persistence of openehr objects in a postgresql db. VirtualEhr provides the service framework and exposure with REST. In this repository, I have added the documentation (in installation), examples scripts and config files (examples). I have also added some libraries to help in the building process.

**Comment by serefarikan** [comment]
Brilliant! I am currently working 24/7 on something (holiday? what holiday?) This will be the first piece of code I'll be looking at when I have a few minutes. Many thanks for the update and well done!
