### ISSUE TITLE
tzid columns are too small

### ISSUE THREAD

**Issue by ralphvanetten** [ethercis/ethercis#10]
In the database the `tzid` column is defined as `VARCHAR(15)` which is too small for zone IDs such as `Europe/Amsterdam`.
In our fork I changed the column to be a `TEXT` instead. (Actually, I replaced all `VARCHAR`s with TEXT for all columns for which the openEHR spec does not specify a maximum length)

**Comment by chevalleyc** [comment]
see [PR#5](https://github.com/ethercis/ehrservice/pull/5/commits)
