### ISSUE TITLE
tzid is not used consistently

### ISSUE THREAD

**Issue by ralphvanetten** [ethercis/ethercis#11]
For instance in `EhrAccess#commit()` the `date_created_tzid` column is not set while in other methods the `date_created_tzid` is set. (but there are other classes/methods where the `date_created_tzid` column is not set)

Related to this, I would recommend to get rid of joda-time and sql timestamps in the internal APIs of ethercis and use java8 date/time instead.

**Comment by chevalleyc** [comment]
see [PR#5](https://github.com/ethercis/ehrservice/pull/5/commits)
