### ISSUE TITLE
building ehrservice is not as easy

### ISSUE THREAD

**Issue by ralphvanetten** [ethercis/ethercis#12]
Currently building ehrservice requires running maven and a couple of platform dependent shell scripts and some manual tinkering as well.
In our fork I've created some gradle build files which allows ehrservice to be build from scratch without manual intervention.
I used gradle because that's what we are most familiar with but we can do it also in maven.

What is your vision on making building ehrservice more userfriendly?

**Comment by ethercis** [comment]
I guess this is related with [PR#5](https://github.com/ethercis/ehrservice/pull/5)
