### ISSUE TITLE
Dependency in VirtualEhr/KnowledgeService

### ISSUE THREAD

**Issue by jakesmolka** [ethercis/ethercis#123]
This line https://github.com/ethercis/VirtualEhr/blob/master/KnowledgeService/pom.xml#L177 is a unresolved dependency for me. I got the files `ecis-ehrdao-1.1.0-SNAPSHOT.jar` and `ecis-ehrdao-1.1.2-SNAPSHOT.jar` but no 1.0.0.

Replacing the string with `${project.version}` seems to solve it but `mvn clean install` fails in a later step anyway, so I don't really know if that's a fix.

**Comment by chevalleyc** [comment]
Yes you are right, it should be ```${project.version}``` , however, at least on my side, the build is successful. What is the outcome of ```mvn clean install``` on your side?

**Comment by chevalleyc** [comment]
Think this has been resolved. Pls reopen if not. Thanks
