### ISSUE TITLE
VirtualEhr - EhrScape API Reference Questions

### ISSUE THREAD

**Issue by jakesmolka** [ethercis/ethercis#124]
When testing (on the test server) against the EhrScape API the mapping for PUT methods in /ehr endpoint seem to be wrong. All three defined methods

- /ehr/{ehrId}/folder
- /ehr/{ehrId}/status
- /ehr/{ehrId}/status/other_details

fail with `No mapping defined for path:rest/v1/ehr/$SOME-ID`. But when reordering to 

- /ehr/status/{ehrId}

it works. Although `folder` and `other_details` fail too (maybe not implemented yet?).

That suggests the paths for that endpoint are in wrong order.

**Comment by jakesmolka** [comment]
That's strange. I was using https://www.ehrscape.com/api-explorer.html (no direct link possible, but click on Electronic Health Records API -> /ehr) and there the order is different to your source.

I hope as the openEHR REST API is written in API Blueprint / apiary some automation can help to implement and test the API in EtherCIS.

**Comment by chevalleyc** [comment]
Yes I get that, but until now we have been using the above pointer as reference... we certainly need to change the endpoints to comply with the (yet to be released) openEHR REST API.

**Comment by jakesmolka** [comment]
Follow up: What documentation was source of ``/composition/convert/tdd`` (or ``.../json``) implementation? I can't find it in https://www.ehrscape.com/reference.html and there are some quirks against https://www.ehrscape.com/api-explorer.html too.

**Comment by chevalleyc** [comment]
There is no implementation of these 'converts' end points. In the context of EtherCIS, I would recommend to implement third party data conversions simply at DB level backed by batch processing (scheduler etc). This is a new chapter to be written, well worth it, since performance is far superior than going through the middleware round trip (not required since EtherCIS deals with a structured data model as opposed to BLOBs or other key-values store approaches).

**Comment by jakesmolka** [comment]
Okay thank you. One last question (for now):
I migrated some of my tests to only honor https://www.ehrscape.com/reference.html but now the first thing that pops up is: POST /session returns `200` on success instead `201` as stated in the reference. Is that intentional? The test server responds `200` too.

PS: I will change the name of the issue to reflect the broader topic.

**Comment by chevalleyc** [comment]
It returns 200 since it does not create a resource (session is a mere token here). 

Regarding discussions, I think it would be better to use Gitter instead of posting issues here (which should be trouble tickets, bugs or RFEs). Tx
