### ISSUE TITLE
Error in Contacts Introspection document

### ISSUE THREAD

**Issue by robtweed** [ethercis/ethercis#125]
Just found this error in the Introspection document for the Contacts template:  IDCR - Relevant contacts.v0

                  {
                    "min": 0,
                    "aql_path": "/content[openEHR-EHR-SECTION.relevant_contacts_rcp.v1]/items[openEHR-EHR-ADMIN_ENTRY.relevant_contact_rcp.v1]/data[at0001]/items[at0030]",
                    "max": 1,
                    "name": "Relationship/ role",
                    "description": "For an informal carer, the personal relationship with the client/carer e.g spouse or friend . For a formal carer, the professional role or responsibility of the carer with respect to the person which should help identify them as being an appropriate contact for an aspect of care, usually a professional role or care pathway name.",
                    "id": "relationship__role",
                    "category": "ELEMENT",
                    "type": "DV_TEXT",

The error is in the "id" property - it should only have one underscore character, ie it should be "relationship_role", not "relationship__role"

**Comment by chevalleyc** [comment]
Thanks, fixed in V1.2
