### ISSUE TITLE
deploy-n-scripts contents are out of date

### ISSUE THREAD

**Issue by serefarikan** [ethercis/ethercis#126]
Greetings. Thanks for the v1.2 update @chevalleyc  Looking forward to taking a look at it. I noticed that the deploy-n-scripts repo is still based on 1.1 though and `gradle flywayMigrate` no longer appears to be working. 
Is it because gradle and flyway is no longer used to set the db up or is there a problem that deserves a dedicated issue? 
Any plans to update deploy-n-scripts contents for 1.2?

**Comment by serefarikan** [comment]
For some reason, github did not send me an email or any updates when you replied, so sorry about the late response and thanks for your response. 

let me qualify my previous message: `gradle flywayMigrate` is working but the problem is that the scripts added/modified for v1.2 do not comply with the expected flyway file naming pattern and when I fix the naming patterns, the scripts themselves fail during execution (details [here](https://github.com/ethercis/ehrservice/issues/16))

So I think the db setup based on gradle can stay as it is for the moment.

**Comment by chevalleyc** [comment]
I've fixed the issue with the wrong function declarations (in fact those were experiments in my dev environment). Pls check. Tx!
