### ISSUE TITLE
Link to pgsql_ehr.ddl in README.md is broken

### ISSUE THREAD

**Issue by IgorBMSTU** [ethercis/ethercis#128]
You should use [this link](https://github.com/alessfg/docker-ethercis/blob/master/postgres/scripts/pgsql_ehr.ddl) 
But maybe it was updated
upd: This is not the only broken link in the readme

**Comment by chevalleyc** [comment]
Please refer to https://github.com/ethercis/deploy-n-scripts for issues related to installation/deployment.
