### ISSUE TITLE
Dependency on JavaFX in VirtualEHR 

### ISSUE THREAD

**Issue by Geisterfalle** [ethercis/ethercis#129]
It looks like there is a dependency on JavaFX in the VirtualEHR project: EhrHttpServerTest.java uses a StringFormatter to create a random EHR ID. This causes some hurdles when you want to use openJDK, as you will require several steps to include JavaFX (respectively openJFX), at least when you use CentOS. I have no concrete suggestion for an alternative, but I guess it would make life easier in the long run (and keep the number of unnecessary dependencies low) to find a less exotic alternative.

**Comment by chevalleyc** [comment]
I posted a fix for this issue. Thanks for the hint. Pls let me know the outcome.

**Comment by chevalleyc** [comment]
Assuming fixed. Pls reopen if needed. Tx
