### ISSUE TITLE
Composition Version Number Does Not Increment Up

### ISSUE THREAD

**Issue by johnmeredith** [ethercis/ethercis#130]
When updating a composition, the version number does not appear to increment. 

`POST
http://cdr.agored.fun:8080/rest/v1/composition?ehrId=d9fda6b1-af8d-4546-9b09-e7c194217a0d&templateId=IDCR - Problem List.v1&committerName=Dr Phil Evans&format=FLAT`

`Request Headers:`
`authorization:"{{Authorization}}"
ehr-session:"sessionId:10.1.2.5-guest-1531373349151--819181299-31"
content-type:"application/json"
auth-token:"{{Auth-Token}}"
cache-control:"no-cache"
postman-token:"9d18d1b4-6c20-4c4a-9285-729f18f08457"
user-agent:"PostmanRuntime/7.1.5"
accept:"*/*"
host:"cdr.agored.fun:8080"
accept-encoding:"gzip, deflate"
content-length:817`

`Request Body:
ctx/composer_name:"Dr Tony Shannon"
ctx/composer_id:"G33567"
ctx/health_care_facility|id:"999999-345"
ctx/health_care_facility|name:"Ripple Valley Hospital NHS"
ctx/id_namespace:"NHS-UK"
ctx/id_scheme:"2.16.840.1.113883.2.1.4.3"
ctx/language:"en"
ctx/territory:"GB"
ctx/time:"2015-10-22T00:11:02.518+02:00"
problem_list/problems_and_issues:0/problem_diagnosis:0/date_time_of_onset:"2000-07-17T12:30:37.553Z"
problem_list/problems_and_issues:0/problem_diagnosis:0/problem_diagnosis_name|code:"299757012"
problem_list/problems_and_issues:0/problem_diagnosis:0/problem_diagnosis_name|terminology:"SNOMED-CT"
problem_list/problems_and_issues:0/problem_diagnosis:0/problem_diagnosis_name|value:"angina pectoris"`

`Response Headers:
date:"Thu, 12 Jul 2018 05:56:49 GMT"
access-control-allow-origin:"*"
content-type:"application/json;charset=UTF-8"
content-length:"228"
server:"Jetty(9.3.z-SNAPSHOT)"`

`Response Body:
compositionUid:"b57a59b9-9812-461a-bd13-aedc84becbf4::ethercis.ripple.org::1"
meta:
action:"CREATE"`

On Update:
`PUT
http://cdr.agored.fun:8080/rest/v1/composition/b57a59b9-9812-461a-bd13-aedc84becbf4::ethercis.ripple.org::1?format=FLAT&templateId=IDCR - Problem List.v1`

`Response Body:
compositionUid:"b57a59b9-9812-461a-bd13-aedc84becbf4::ethercis.ripple.org::1"
meta:
href:"rest/v1/composition?uid=b57a59b9-9812-461a-bd13-aedc84becbf4::ethercis.ripple.org::1"
action:"UPDATED"`

The versnio number has not incremented.

**Comment by chevalleyc** [comment]
I've committed a fix (CompositionService.java). Pls recompile CompositionService. Tx

**Comment by chevalleyc** [comment]
Assuming fixed. Pls reopen if needed. Tx

**Comment by freshehr** [comment]
@chevalleyc The compositionUId is updating correctly but not the meta statement ...

```
{
    "compositionUid": "edae37eb-5b57-4da4-a7f8-952d66d1894d::nes.ripple.foundation::2",
    "meta": {
        "href": "rest/v1/composition?uid=edae37eb-5b57-4da4-a7f8-952d66d1894d::nes.ripple.foundation::1"
    },
    "action": "UPDATED"
}
```
