### ISSUE TITLE
Unable to generate FLAT example if OPT contains 'Choice' data type with mutliple data options

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#140]
OPTs containing choice data types with more than one data type options are imported properly without any error. However the template example API returns 200 success, but returns empty FLAT example. If the data types are constrained to one in template, it starts working.

Sample OPTs
[EHRN Medication order (3).zip](https://github.com/ethercis/ethercis/files/2205902/EHRN.Medication.order.3.zip)
One dated 17th has problem, but the one dated 18th works as the data types have been constrained

Template data set
[EHRN Medication order_set.zip](https://github.com/ethercis/ethercis/files/2205908/EHRN.Medication.order_set.zip)

**Comment by chevalleyc** [comment]
Hi Dileep,

Could you please be more specific and indicate:

- expected behavior/result and actual behavior/result
- steps to reproduce the issue

Many thanks -- Christian

**Comment by chevalleyc** [comment]
I'm not quite sure how Marand FLAT handles CHOICE, perhaps @freshehr knows?

**Comment by chevalleyc** [comment]
@dileep-ehr  not exactly what you expect, but could you use [template introspection](https://github.com/ethercis/ethercis/blob/master/doc/OPT%20introspection.md) instead?

**Comment by dileep-ehr** [comment]
This issue is not important now with the template introspection option. We can consider it resolved
