### ISSUE TITLE
populate_concept scripts not working

### ISSUE THREAD

**Issue by Geisterfalle** [ethercis/ethercis#142]
Hi Christian,

it looks like that the above mentioned files are not up-to-date as they are still pointing to com.ethercis.dao.access.support.TerminologyReader which is not available anymore and has been replaced by V3_terminology. When you try to install the postgres database on windows, this will likely cause confusion. 

Birger

**Comment by chevalleyc** [comment]
Pls refer to https://github.com/ethercis/deploy-n-scripts for issue related to installation/deployment. Tx
