### ISSUE TITLE
Wrong result for EHRs in AQL

### ISSUE THREAD

**Issue by Geisterfalle** [ethercis/ethercis#144]
Hi Christian,

on the latest version of EtherCIS, the following query provides a wrong result set:

localhost:8080/rest/v1/query

{"aql":
"
select e/ehr_id/value
from EHR e
"}

It looks like EHR IDs are only selected if there exists at least one composition for them. Example: there are 6 EHR IDs in the postgres database but only 3 EHR IDs are returned by the above statement as these are the only ones that have compositions. When I add a composition to one of the EHR IDs that have not been returned, next time, the query will also fetch it.

**Comment by chevalleyc** [comment]
Hi Birger, I've committed a change (pb was with joins). Pls check

**Comment by Geisterfalle** [comment]
This solved the problem! Thx!

**Comment by chevalleyc** [comment]
Assuming fixed now, please reopen if needed. Tx
