### ISSUE TITLE
Problem with AQL parsing when EHR-ID not at top position in select 

### ISSUE THREAD

**Issue by Geisterfalle** [ethercis/ethercis#145]
Hi Christian,

I see the following behavior when querying using AQL:

{"aql":
"
select
    e/ehr_id/value,
    b/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude,
    b/data[at0002]/events[at0003]/time/value
from EHR e
contains COMPOSITION a
contains OBSERVATION b[openEHR-EHR-OBSERVATION.body_temperature.v1]
"
}

works just fine. However, when I'm putting e/ehr_id/value at a different position like

    b/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude,
    b/data[at0002]/events[at0003]/time/value,
    e/ehr_id/value

I get the following output:

<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /rest/v1/query. Reason:
<pre>    #1.0.0 Invocation exception to method:query:java.lang.IllegalArgumentException: AQL exception:ERROR: syntax error at or near &quot;DISTINCT&quot;,  Position: 663</pre></p>

No idea why it referes to the DISTINCT keyword and this works also with EHRSCAPE.

**Comment by chevalleyc** [comment]
I pushed a fix for this issue. Pls check. Thanks!

**Comment by Geisterfalle** [comment]
Thx, this works now! :) Just one follow up question: it looks like that the order of the selected elements within the query is not the same as in the corresponding result set:

b/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude,
e/ehr_id/value,
b/data[at0002]/events[at0003]/time/value


becomes

 "FIELD_2" : "2018-08-07T21:02:56.416+02:00",
 "FIELD_0" : "57.2",
 "ehr_id/value" : "a5c8993e-51af-4565-a20e-eb31465de750"


Is this intended behavior? We can move this to a separate issue if needed.

**Comment by chevalleyc** [comment]
Good point :) We actually didn't see that since the fields were always named ('as xyz'). A separate issue is a good idea (albeit low priority IMO). Cheers

**Comment by chevalleyc** [comment]
Assuming it's fixed now. Pls reopen if needed. Tx
