### ISSUE TITLE
Handling of multiple instances of one archetype in the same OPT in AQL

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#148]
We are using a service request template with the following structure
[openEHR-EHR-COMPOSITION.request.v1]
        [openEHR-EHR-INSTRUCTION.request.v0]
[openEHR-EHR-CLUSTER.organisation.v0]
    [openEHR-EHR-CLUSTER.person_name.v1]
[openEHR-EHR-CLUSTER.organisation.v0]
    [openEHR-EHR-CLUSTER.person_name.v1]

The template uses the same archetypes in more that one instance ([openEHR-EHR-CLUSTER.organisation.v0] & [openEHR-EHR-CLUSTER.person_name.v1]) to represent requester and requested from. 
When I raised the topic in OpenEHR mailing list Ian pointed me to the following link https://github.com/RippleOSI/Ripple-openEHR/tree/master/docs/bindings/Current%20Ripple%20Headings/Referrals
He also mentioned that this was not working n Ethercis when he tested in the past. We also tried, but could not get it to work. 
Has something been done regarding this recently? Is there any alternative ways this is handled in Ethercis?

regards

**Comment by chevalleyc** [comment]
Please post an actual scenario to reproduce the issue with template, test data, transaction, expected results, actual result. Thanks.
