### ISSUE TITLE
OpenEHR requirements for anonymizing EHR 

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#149]
Hi,
OpenEHR specifications include anonymizing EHR. However EtherCIS  keeps a map of EHRID to personID internally. Does this meet the [openEHR EHR Platform Conformance](https://www.openehr.org/releases/CNF/latest/docs/openehr_platform_conformance/openehr_platform_conformance.html) requirements?

IAs per the openEHR Platform Abstract Service Model EHR_SERVICE keeps all EHR data and the mapping in EHR_INDEX. In [OpenEHR platform model](https://www.openehr.org/releases/SM/latest/docs/openehr_platform/openehr_platform.html#_openehr_platform_model) section they are shown as separate services.

regards

**Comment by freshehr** [comment]
Hi dileep. Good question. My understanding is that the underlying spec recognises that having a separate ehr index is the most pure approach, it is allowable for the ehr object to carry subjectId and for the ehr index service to be part of the ehr service. Marand Thinkehr works like this. We may need to adjust the conformance docs if this is not clear.

**Comment by dileep-ehr** [comment]
Thanks Ian,

However I feel that for EHR to remain truly anonymous, EHR_INDEX should not
be inside the EHR server. That way even if the EHR server is compromised,
anonymity is maintained. That is the way we have implemented our
EHR.NETWORK platform. We have EtherCIS, our own demographic server and a
AAA server that contains EHR_INDEX and EHR_ACCESS.

That said there is no lack of clarity in conformance docs as it provides
for flexibility in implementation. Presently the conformance docs does not
seem to include checking for anonymity of EHR and so may have to include
limits to implementation flexibility when that is included. Otherwise we
can have a single integrated service that can include EHR, EHR_INDEX and
Demographics and still satisfy conformance requirements.

regards

Dileep V S
*Founder*
HealtheLife Ventures LLP
m: +91 9632888113
a: 106, Innovation Centre, IIIT, Electronics City, Bangalore 560100
w: healthelife.in  e: dileep@healthelife.in

**Comment by chevalleyc** [comment]
Not an EtherCIS specific issue.
