### ISSUE TITLE
ecis-ehrdao depends on ripple-patient-summary

### ISSUE THREAD

**Issue by ralphvanetten** [ethercis/ethercis#15]
When the ripple-patient-summary module was added, it made changes to the database, the jooq generated sources and the `OptTemplateRef` and `TemplateRefSetter` classes where added to `ecis-ehrdao`.
These changes make the `ecis-ehrdao` dependent on the ripple-patient-summary module. I've would expected the ripple-patient-summary to be a separate module in its own repo so ehrservice will function and can be build without the ripple-patient-summary. What do you think?

**Comment by ethercis** [comment]
Indeed, the tables: heading, template and TemplateHeadingXref have been added and used by one utility class ehrdao::com.ethercis.doa.access.util.OptTemplateRef. 

This change, although used by the - DB side only procedures - Ripple Patient Cache is not specific to Ripple. AFAIK there are similar functionalities in Think!Ehr (Headings). Further, the Template table is needed to implement a future referential integrity checking for table Entry (which reference a template by a string) and future Template caching in the DB.

**Comment by ralphvanetten** [comment]
Ah, ok, then the only issue might be that it could use a more generic name :smiley:

**Comment by tony-shannon** [comment]
thanks both, as far as I know the Patient Cache discussed here is being used to support this requirement
See the screenshot to explain;
![image](https://user-images.githubusercontent.com/939996/27480162-c6446be4-580e-11e7-9110-c1155058fe5b.png)


The requirement is that if Im a busy clinician I want to be able to take a look at a MultiPatientView and see with one look at 
-get an overview of patients - by the count of their "issues" /(gives an idea of workload for example) (in this example Ivor Cox has 33 Orders so likely has the most co morbidities) 
-get overview of patients - with datetime stamps of past/recent activity (this is esp helpful to tracking patients) (Emma Gallagher in this example hasnt had any results since 1970 so she likely has enjoyed 47 years of good health)

You get the idea its a guide to the MultiPatient Group

So the requirement is that the repository keeps a "cache" of counts & datetime stamps per clinical concept (archetype eg orders/results in this case)

Hope that helps explain the requirement so can guide the naming of the related code module

**Comment by ethercis** [comment]
Thanks for giving more details on this Tony. On a code base standpoint, there is no reference to Ripple Patient Summary. What has been added, quite rightly so, are references to Templates and Headings. Pretty generic isn't it?

**Comment by tony-shannon** [comment]
thanks Christian
Am sure the code involved should be pretty generic & reusable.
Can I ask where the ripple-patient-summary/cache references are found?
These should be removed and replaced with a more generic name/reference.
thanks
Tony

**Comment by ethercis** [comment]
To close this topic: **there is NO dependency on ripple-patient-summary in ehrdao**. The only place where it is actually mentioned is in a test and as a **composition**.

**Comment by ralphvanetten** [comment]
Why are you saying there is no dependency on ripple-patient-summary in ehrdao? If you don't create the tables mentioned in the ripple-patient-summary you can not regenerate jooq and you can not compile ehrdao. ehrdao uses tables which are only created by some script in ripple-patient-summary.
So there sure is a dependency between them.

I was attempting to build ehrservice from scratch, without ripple-patient-summary, and regenerate jooq. This does not work without first running some of the database scripts in ripple-patient-summary.

As you mentioned earlier:

> Further, the Template table is needed to implement a future referential integrity checking for table Entry (which reference a template by a string) and future Template caching in the DB.

If it is such an integral and generic part of the DB, then why are the scripts for creating those generic tables in a module called ripple-patient-summary? 
The solution then would be to move those generic scripts to same place as the rest of the database scripts, preferably under control of some database schema migration tool (but that's another issue)

I do agree the rest of the patient summary is really generic and the ripple use case can be seen as an example of how to implement your own summary.
However the way the database schema is managed and how these database scripts are organized could use some improvement.

**Comment by ethercis** [comment]
Will update script. ThanksOn Jun 27, 2017 1:01 PM, Ralph van Etten <notifications@github.com> wrote:Why are you saying there is no dependency on ripple-patient-summary in ehrdao? If you don't create the tables mentioned in the ripple-patient-summary you can not regenerate jooq and you can not compile ehrdao. ehrdao uses tables which are only created by some script in ripple-patient-summary.
So there sure is a dependency between them.
I was attempting to build ehrservice from scratch, without ripple-patient-summary, and regenerate jooq. This does not work without first running some of the database scripts in ripple-patient-summary.
As you mentioned earlier:

Further, the Template table is needed to implement a future referential integrity checking for table Entry (which reference a template by a string) and future Template caching in the DB.

If it is such an integral and generic part of the DB, then why are the scripts for creating those generic tables in a module called ripple-patient-summary?
The solution then would be to move those generic scripts to same place as the rest of the database scripts, preferably under control of some database schema migration tool (but that's another issue)
I do agree the rest of the patient summary is really generic and the ripple use case can be seen as an example of how to implement your own summary.
However the way the database schema is managed and how these database scripts are organized could use some improvement.

**Comment by janmarc** [comment]
Hi @ethercis,

Please remove the word ripple, that is it.., there is nothing else behind the remark. So just name it patient-summary.

Jan-Marc
