### ISSUE TITLE
Missing classes in EtherCIS VirtualEhr

### ISSUE THREAD

**Issue by GeorgFette** [ethercis/ethercis#150]
I try to compile the EtherCIS project. I managed to compile the 
openehr-java-libs as well as the ehrservice projects. But I have a 
problem with the VirtualEhr:
In the project ecis-vehr-service there is a class FileDispatchMapper 
that uses the two classes com.ethercis.ehrserver.servicemap.Action and 
com.ethercis.ehrserver.servicemap.MapperDociument. However, there is no 
namespace com.ethercis.ehrserver and so those two classes also do not exist.
What am I missing ? Did i forget to import a missing project that 
includes those classes ?

**Comment by chevalleyc** [comment]
I have added a note in the README (it was there before...) explaining how to integrate external libraries with a local Maven repository.
