### ISSUE TITLE
consider using an existing solution like flyway to manage the database schemas

### ISSUE THREAD

**Issue by ralphvanetten** [ethercis/ethercis#16]
Would you consider using a solution like flyway (but there are others) in favor of the shell and sql script combination you currently have?

Using such a solution makes managing database schemas and making sure the servers have the latest schemas installed much easier.

**Comment by ethercis** [comment]
Yes that's a great idea. The target DB could be hosted in one of our ethercis.net host. Let's have a chat about it :)

**Comment by chevalleyc** [comment]
see [PR#5](https://github.com/ethercis/ehrservice/pull/5/commits)
