### ISSUE TITLE
Removing sample templates after installing v 1.2.0

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#163]
When Ethercis V 1.2.0 is installed, some OPTs are installed by default. If I want to remove them can I just delete them from the operational_templates folder and restart the server? 

Are any database indexes created when the server is started? Do we need to also reset the database to completely remove them?

**Comment by chevalleyc** [comment]
Sure, you can cleanup entirely operational_templates. Templates are there to help getting started.
Indexing is done on joins, but that's about it. Proper indexing is under the responsibility of the DBA.
