### ISSUE TITLE
Securing Ethercis database connection to the db

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#164]
The v1.2.0 installation docs mention about setting local connections to trust in pg_hba.conf. This is not very secure for a production deployment. The db password configured in env.rc does not seem to be used to connect to the DB server because of the trust setting and connections from any user is allowed.

Is there any documentation to set this up for production?

**Comment by chevalleyc** [comment]
Please use version v1.3.0. It supports certificate for the connection to the DB, JWT and RLS. This can address most of the security issues and more.

**Comment by dileep-ehr** [comment]
Thanks. But I do not see version 1.3 in the repository. Can you help?

regards
Dileep V S
*Founder*
HealtheLife Ventures LLP
m: +91 9632888113
a: 106, Innovation Centre, IIIT, Electronics City, Bangalore 560100
w: healthelife.in  e: dileep@healthelife.in

**Comment by chevalleyc** [comment]
I'm afraid you'll have to compile branch v1.3.0 by yourself to compile the required jars.
