### ISSUE TITLE
Errors being returned as HTML - EtherCIS V1.3 - ReSPECT Template

### ISSUE THREAD

**Issue by PhilBarrett** [ethercis/ethercis#173]
Expected behaviour is that errors are returned as a parseable JSON response. Currently receiving HTML

```

< html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 #1.0.0 Invocation exception to method:create:java.lang.IllegalArgumentException: No template found...</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /rest/v1/composition. Reason:
<pre>    #1.0.0 Invocation exception to method:create:java.lang.IllegalArgumentException: No template found...</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/>

</body>
</html> 

```

**Comment by chevalleyc** [comment]
Please specify the transaction giving this result.

**Comment by tony-shannon** [comment]
Details from Chat from @robtweed

> Hi Ian - just doing some tests of the Respect form on EtherCIS. trying to POST a new one with this:

> http://ethercis1.3-test.ripple.foundation:8080/rest/v1/composition?templateId=RESPECT_NSS-v0&format=FLAT&ehrId=91faff0b-cb5d-4f93-bf37-a99165aba439

> got this error:
500 #1.0.0 Invocation exception to method:create:java.lang.IllegalArgumentException: No template found...

> I'm using the template name as per here: https://github.com/RippleOSI/Ripple-openEHR/blob/master/docs/bindings/Current%20Ripple%20Headings/NSS%20ReSPECT/NSS_RESPECT.md

**Comment by freshehr** [comment]
Yup but the template itself needs to be loaded into that EtherCis instance.

https://github.com/RippleOSI/Ripple-openEHR/blob/master/technical/operational/RESPECT_NSS-v0.opt

**Comment by tony-shannon** [comment]
thanks Ian @freshehr, Christian has loaded up already afaik

**Comment by chevalleyc** [comment]
Nope. This one is not loaded AFAIK
Also, please note that the HTTP header response indicate a status 500 with a corresponding error in attribute x-error-message. I appreciate the comment about HTML, but the client should interpret the HTTP header.
Finally: PLEASE STOP POSTING ERROR RELATED TO SPECIFIC TEST DEPLOYMENT INTO GITHUB. GITHUB IS NOT THE PLACE TO DISCUSS DEPLOYMENT ISSUES/SCENARIO. POST ONLY ISSUE RELATED TO THE CODE BASE. THANKS.
