### ISSUE TITLE
Duplicate entry in ehr.event_context_history

### ISSUE THREAD

**Issue by chevalleyc** [ethercis/ethercis#177]
Likely that upon updating a composition, event_history is duplicated (causing a potential issue when performing a join)

**Comment by freshehr** [comment]
possibly related to #178 ??

**Comment by chevalleyc** [comment]
Checked running it with a new fresh scenario. Observed duplicates may have been created on my test box by running backups with disabled triggers.

**Comment by chevalleyc** [comment]
Fixed this duplicate calls of ContextAccess::update from FlatJsonHandler. This explains why this issue has been unnoticed whenever tests have been performed with another format (e.g. not FLAT). Please test.
