### ISSUE TITLE
Recomended format for composition commits - FLAT or ECISFLAT

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#183]
As we were testing ethercis, we noticed some difference in the way data gets stored using FLAT and ECISFLAT compositions. They also seem to have some impact on the AQL as well.

At this stage which the preferred(recomended) format to use for compositions? FLAT or ECISFLAT? Will it be OK for an instance to have both types of compositions?

**Comment by freshehr** [comment]
It should be irrelevant. Both are ultimately simply serialisations of the object model. Only the RAW XML and JSON formats are 'official' openEHR standards though we are discussing developing a FLAT or STRUCTURED format. Can you give some examples of the differences and possible impact of AQL?

**Comment by dileep-ehr** [comment]
We have been testing V1.2.0 with a mix of FLAT and ECISFLAT compositions and seem to be getting some erratic behavior where the AQL does not return all values sometimes and none sometimes. Unable to document the correct steps to reproduce, since the pattern is erratic. Will do more tests again(1.2.0 & 1.3.0) and try to document the issues.

Mean while these are some of the things that we have observed 

1. Context/location - FLAT does not seem to support this ("encounter/context/location":"Room 202" throws error). ECISFLAT seems to accept ("/context/location": "Room 102",)
2. DV-CODED_TEXT in DV_TEXT - FLAT commits properly using separate lines for value, code & terminology. ECISFLAT saves it as a text string if passed using the DV_CODED_TEXT syntax (SNOMED CT::712823008|Acute depression|). So the AQLs return different values (#172)
3. DV_IDENTIFIER - Not accepted in ECISFLAT (Does not recall if it works with FLAT, will check and update (#169)

**Comment by chevalleyc** [comment]
Re erratic AQL, we are using EtherCIS AQL for several years, this has been well tested. There might be bugs (as expected), but nothing random AFAIK. Thus, if you cannot figure out why a particular issue occurs, we can just assume the problem is on the client side.

Re 2. This is a request for enhancement and needs prioritization along with other tasks. 
Re 3. As above.

That said, ECISFLAT processing is much faster than FLAT (by a factor 4 to 5 depending on the complexity.). The payload expression is also simpler since it doesn't need a specific tool to identify json keys from template designer (it is just cut'n paste).

**Comment by dileep-ehr** [comment]
By saying erratic, the idea was not to imply that aql per se is inconsistent. In a mixed environment where we had both FLAT and ECISFLAT compositions, sometimes, the results confused us. This is possibly because of the variations of feature support between the two (as I had indicated before).

That said we faced some problems with generation of FLAT template examples with some OPTs(especially the more complex ones such as medication order) as the server returned parse error,  but have got consistent success with ECSFLAT generation. Also, as you had indicated, the ECISFLAT path syntax being consistent with the aql paths is a big advantage. Given our low load test environment, we have not had a chance to experience the performance advantage, but take your word for it

My question was more to know if both the formats would be supported into the future or is the balance tilting in favour of one or the other.

**Comment by freshehr** [comment]
"DV-CODED_TEXT in DV_TEXT - FLAT commits properly using separate lines for value, code & terminology. ECISFLAT saves it as a text string if passed using the DV_CODED_TEXT syntax (SNOMED CT::712823008|Acute depression|). So the AQLs return different values (#172)"

That does sound like a bug - it should parse into a DV_CODED_TEXT and end up exactly the same - suggest you report it.

Right now there are 2 canonical 'RAW' serialisation formats that are standardised in openEHR - XML and JSON.

I think t is still an open question as to which (if any) are the best 'flattened' formats. The only one that is well standardised is the TDS (XML) format developed by Ocean but supported by a number of CDRs.

There is definitely a need to standardise one or two of the range of 'proprietary' formats out there but I suspect we may end up with a few, as the potential consumers/preferences are all a little different.  I would assume that both formats will be supported for some time, though both may morph/merge with others e.g. the FLAT format that DIPS use is pretty similar to ECIS FLAT.

We might also see new approaches e.g based around GraphQL. I don't think there is a compelling one-true solution as yet.

**Comment by dileep-ehr** [comment]
I have also reported another bug #167, which seems related to #172. The issue seems to be that ECISFLAT does not look at the format of the incoming data to decide the data format to be used for committing the data.  
At template index time one default data type is assumed and validated against irrespective of the type of data that is coming in. If the incoming does not match the assumed format server gives and error. 
Ideally we should look at the incoming data format, validate it against all possible data formats before giving an error

**Comment by chevalleyc** [comment]
Re 'looking at the format of data' I am very cautious about implementing some sort of 'smart' to figure out a data type (I have seen first hand a costly disaster due to some smart assumption like this). ECISFLAT does support some explicit CHOICE formulation whenever multiple data types are supported explicitly defined in the template (see https://github.com/ethercis/ethercis/blob/master/doc/flat%20json.md). However, whenever polymorphism is used, I would rather have some explicit class cast passed in the payload (f.e. "@DvCodedText|terminology::code|value|"). WDYT?

**Comment by dileep-ehr** [comment]
Thanks for the pointer about the support for CHOICE. I had not noticed it.
Will try and update

Being cautious about figuring out data type from payload does make sense.
Your suggestion of the information being passed explicitly with the payload
should work just fine. But a consistent pattern for both CHOICE and
polymorphism cases may be a good idea (f.e.
"@DvCodedText|terminology::code|value|")

regards
Dileep V S
*Founder*
HealtheLife Ventures LLP
m: +91 9632888113
a: 106, Innovation Centre, IIIT, Electronics City, Bangalore 560100
w: healthelife.in  e: dileep@healthelife.in
