### ISSUE TITLE
I_KnowledgeCache could be simplified

### ISSUE THREAD

**Issue by ralphvanetten** [ethercis/ethercis#19]
The `I_KnowledgeCache` interface could be simpler. The ehrservice only uses 3 or 4 methods and the rest is for creating REST responses (which IMHO belongs in VirtualEhr) and various management functions used by other parts of the system.
Having such an extensive interface makes it more difficult to replace the knowledge cache with another implementation and couples the knowledge-cache to the REST API.

Also, besides providing access to the archetype models and templates, it is also responsible for caching newly generated composition. This seems to be a bit odd.

Further, using plain maps will cause concurrency issues when accessing the knowledge cache from multiple threads. Cache2k seems to be a better fit to do the actual caching. (We've made a simplified version of the knowledge cache using cache2k)

**Comment by ethercis** [comment]
Re **also responsible for caching newly generated composition** it is actually a caching of **generic** compositions associated to templates. These cached compositions do not store user defined values. They are used as serialized templates whenever a binding is performed (XML, data from DB etc.). This is to optimize this otherwise costly process.

**Comment by ethercis** [comment]
Very valid point about caching using cache2k. I will add this point into the roadmap. Thanks!

**Comment by ralphvanetten** [comment]
Re **also responsible for caching newly generated composition**

The reason I mentioned this is because if you want to implement your own knowledge cache, then you also have to implement the caching of the compositions.

It seems to me a separate composition cache would be better. This separate composition cache would then use the knowledge cache and the composition builder to construct the composition.
So instead of building the composition and then storing the composition in the knowledge cache, you ask the composition cache for the composition. If the composition is in the cache it will return it, if the composition is not there the composition is build first. This will also prevent some possible concurrency issues if multiple threads need the same composition.

**Comment by ethercis** [comment]
I put this request into our Roadmap for the second half of this year. Thanks!
