### ISSUE TITLE
uid with prefix fails 

### ISSUE THREAD

**Issue by freshehr** [ethercis/ethercis#191]
THe following json fails unless the 'ethercis-' prefix is removed from the uid at 

`mdt_output_report/referral_details/mdt_referral/request:0/_uid": "ethercis-d41071d2-6543-4677-a6c9-c3fe7337d78a",`

works fine on ThinkEhr and I can't see that the specs disallow the prefix, although a suffix like ':ethercis' is preferred

```Error 500 #1.0.0 Invocation exception to method:create:java.lang.IllegalArgumentException: failed to create new instance of HIER_OBJECT_ID: IllegalArgumentException: wrong format, valueMap: {
    value=java.lang.String:ethercis-d41071d2-6543-4677-a6c9-c3fe7337d78a}</title>```

```
{ "ctx/composer_name": "Dima Dima",
  "ctx/health_care_facility|id": "999999-345",
  "ctx/health_care_facility|name": "Home",
  "ctx/id_namespace": "NHS-UK",
  "ctx/id_scheme": "2.16.840.1.113883.2.1.4.3",
  "ctx/language": "en",
  "ctx/territory": "GB",
  "ctx/time": "2019-09-18T00:00:00+01:00",
  "mdt_output_report/referral_details/mdt_referral/request:0/_uid": "ethercis-d41071d2-6543-4677-a6c9-c3fe7337d78a",
  "mdt_output_report/referral_details/mdt_referral/request:0/service_name": "MDT referral",
  "mdt_output_report/referral_details/mdt_referral/request:0/timing": "R2/2016-12-19T18:00:00Z/P2M",
  "mdt_output_report/referral_details/mdt_referral/narrative": "MDT request",
  "mdt_output_report/referral_details/mdt_referral/service_team": "New Service",
  "mdt_output_report/referral_details/referral_requested/ism_transition/current_state|code": "526",
  "mdt_output_report/referral_details/referral_requested/ism_transition/careflow_step|code": "at0026",
  "mdt_output_report/referral_details/referral_requested/service_requested": "MDT Referral",
  "mdt_output_report/referral_details/referral_requested/time": "2016-01-05T00:00:00Z",
  "mdt_output_report/history/question_to_mdt/question_to_mdt": "Some Question",
  "mdt_output_report/plan_and_requested_actions/recommendation/meeting_discussion": "Some DIscussion" }
```
Template is at 
https://github.com/RippleOSI/Ripple-openEHR/blob/master/technical/operational/IDCR%20%20-%20Minimal%20MDT%20Output%20Report.opt

**Comment by chevalleyc** [comment]
The supported uid is a UUID (specified in openEHR spec): "Model of the DCE Universal Unique Identifier or UUID which takes the form of hexadecimal integers separated by hyphens, following the pattern 8-4-4-4-12 as defined by the Open Group, CDE 1.1 Remote Procedure Call specification, Appendix A. Also known as a GUID.". I fail to understand the justification of a "prefixed" UID. Could you please give more pointers to help me understand this? Tx

**Comment by chevalleyc** [comment]
I guess this issue is for a HIER_OBJECT_ID

**Comment by chevalleyc** [comment]
The expected syntax for a HierObjectID (from UidBaseID) is according to `root::extension` :
```
<root>::<SIMPLE_UUID_PATTERN>|<ISO_OID>|<internet ID>
```
root is any string (f.e. `ethercis`) the double colons are required (`::`)

*SIMPLE_UUID_PATTERN*
This is the standard UUID in the DCE format: 8-4-4-4-2  (Open Group CDE 1.1 RPC specs)

*ISO OID*
A dotted tree of digits (https://en.wikipedia.org/wiki/Object_identifier) 1.1, 1.1.2, 1.3.4.5 etc.

*Internet ID*
A dotted sequence of strings made of ASCII letter, digit or underscore (no `-`). F.e. `ethercis.ripple.org`

NB. A free text is therefore not accepted as a valid HierObjectID

**Comment by freshehr** [comment]
Thx @chevalleyc - this is actually a UID_BASED_ID -> ACTIVITY.uid is the RM attribute, but it looks as if the uid being sent would still not be valid as a UID, with that prefix.

I found that sending the .uid as 
`"mdt_output_report/referral_details/mdt_referral/request:0/_uid": "d41071d2-6543-4677-a6c9-c3fe7337d78a::ethercis",`

works ok and have advised the team to change their uid generation method. 

However, technically this rm attribute is a UID_BASED_ID not a HIER_OBJECT_ID so not sure if might want to check that in case of future issues.

I think we can close this issue

**Comment by freshehr** [comment]
Ah - I see now that UID_BASED_ID is an abstract class, so HIER_OBJECT_ID is correct. Definitely close this issue!!

**Comment by chevalleyc** [comment]
Thanks @freshehr
