### ISSUE TITLE
Format for runtime name constraining in ECISFLAT

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#194]
What is the correct format for applying runtime name constraint for a node using ECISFLAT.

**Comment by freshehr** [comment]
"personal_notes/clinical_synopsis:0/_name|value": "Patient Note",
see
https://github.com/RippleOSI/Ripple-openEHR/blob/master/docs/bindings/Current%20Ripple%20Headings/Personal%20notes/instance/1/Personal%20Notes%201.json

Ian

Dr Ian McNicoll
mobile +44 (0)775 209 7859
office +44 (0)1536 414994
skype: ianmcnicoll
email: ian@freshehr.com
twitter: @ianmcnicoll



Director, freshEHR Clinical Informatics Ltd.
CCIO inidus Ltd. ian@inidus.com
Co-Chair, openEHR Foundation ian.mcnicoll@openehr.org
Hon. Senior Research Associate, CHIME, UCL
