### ISSUE TITLE
Does Ethercis allow saving draft compositions?

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#21]
Does Ethercis support saving and retrieval of draft compositions(version lifecycle state=incomplete)? These are saved either automatically by the UI or by the composer for review and commit later(version lifecycle state=complete).

**Comment by ethercis** [comment]
Contribution as a 'state' attribute, which is an enum type: complete, incomplete, deleted. All compositions are associated to a contribution (see [change control in the EHR](http://www.openehr.org/releases/RM/latest/docs/ehr/ehr.html#_change_control_in_the_ehr) for more details on this. The state is set during a commit/update/delete (internally though at this stage). To date, the REST API does not deal with contribution state. To add this as a parameter, CompositionService should be modified (and related store methods).

**Comment by dileep-ehr** [comment]
Thanks for the reply. I did see the 'state' attribute for contributions, but was not sure about how it is set. Thanks for clarifying that it is set internally now.

However I see a problem in making this a contribution attribute as, in my opinion, it should be a composition version lifecycle state.  Current treatment could work as long as we have a one-to-one relationship between contribution and composition. When we commit more than one composition in one contribution, we may need to set different 'state' values for each composition. Let me know your thoughts on this.

**Comment by ethercis** [comment]
Yes you are right re 1-to-1 relationship contribution/composition. At the moment, that's what we have when a composition is committed, one contribution is created. There is no support for multiple compositions in one contribution (although the standard does specify this)

**Comment by dileep-ehr** [comment]
Thanks
