### ISSUE TITLE
List of 'Context' attributes available in Ethercis

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#22]
From the example JSON files generated, I can see that Ethrcis supports the following 'context' attributes - language, territory, composer(internal and external IDs in FLAT format), healthcare facility, start time and setting. Does it support any other 'context' attributes viz. participation. 

Also 'end time' seems to be internally set, probably from the commit time.  Can we pass it as a attribute in contribution?

**Comment by ethercis** [comment]
Yes context attributes are supported (see PathValue::assignContextAttributes for more). For example, an array of participation can be set as:

<pre><code>
        kvPairs.put("/context/participation:0|function", "Oncologist");
        kvPairs.put("/context/participation:0|name", "Dr. Marcus Johnson");
        kvPairs.put("/context/participation:0|identifier", "1345678");
        kvPairs.put("/context/participation:0|mode", "face-to-face communication::openehr::216");
        kvPairs.put("/context/participation:1|function", "Pediatric");
        kvPairs.put("/context/participation:1|name", "Dr. Mabuse");
        kvPairs.put("/context/participation:1|identifier", "99999-123");
        kvPairs.put("/context/participation:1|mode", "face-to-face communication::openehr::216");
</code></pre>

Please note the particular syntax for mode (a DvCodedText) in the form of
`<value>::<terminologyId>::<code>

**Comment by ethercis** [comment]
Context end_time can be set with:
``"/context/end_time": "2016-11-22T14:08:22+07:00"``

**Comment by dileep-ehr** [comment]
Thanks. Can you explain 'see PathValue::assignContextAttributes for more' little bit more. I am not sure where to look.

**Comment by ethercis** [comment]
I meant look in module 'core', class PathValue.java, method assignContextAttributes.

You could also have a look to [ecisflat ](https://github.com/ethercis/ethercis/blob/master/doc/flat%20json.md) doc, the example show most of context attributes  (note to self: I should update the doc!). 'other_context' is an archetyped item structure. For example:

<pre><code>
        "/context/other_context[at0001]/items[at0005]": "complete",
        "/context/other_context[at0001]/items[openEHR-EHR-CLUSTER.distribution.v1]/items[at0006]": "2015-10-21T10:00:00",
        "/context/other_context[at0001]/items[openEHR-EHR-CLUSTER.individual_personal_uk.v1]/items[openEHR-EHR-CLUSTER.person_name.v1]/items[at0022]": "true",
        "/context/other_context[at0001]/items[openEHR-EHR-CLUSTER.individual_personal_uk.v1]/items[openEHR-EHR-CLUSTER.person_name.v1]/items[at0014]": "2014-10-15::2022-12-31"
</code></pre>

**Comment by dileep-ehr** [comment]
As part of our testing we are documenting our learning for internal use. We can share them, if you feel that will help you with the documentation part. Or in case you want me to help with any specific documents, I can also do that.

**Comment by ethercis** [comment]
Yes that's very kind of you, much appreciated. I am setting up a new documentation site (docs.ethercis.org). If you could contribute to it (especially on the API, deployment side) that would be great!

**Comment by dileep-ehr** [comment]
Always ready to help!! Do let me know how.
I have setup Ethercis on Ubuntu and on AWS and have documentation on those. We are also getting some skills on using the APIs. Those could be the starting points. I can continue picking your brain to fill in the missing parts. Another area to document is the DB schema and how the columns are populated.

**Comment by ethercis** [comment]
I put this into the documentation TODO. Thanks!

**Comment by dileep-ehr** [comment]
Thanks. My offer to help with documentation is still open. I need to know
how I can do that.

regards

Dileep V S
*Founder*
HealtheLife Ventures LLP
m: +91 9632888113
a: 103, Innovation Centre, IIIT, Electronics City, Bangalore 560100
w: healthelife.in  e: dileep@healthelife.in
