### ISSUE TITLE
'iLike/Like' keyword in AQL causes error

### ISSUE THREAD

**Issue by freshehr** [ethercis/ethercis#26]
Use of like or ilike causes an error
e.g.
`select e/ehr_id/value as ehrId   from EHR e   contains COMPOSITION a   contains EVALUATION a_a[openEHR-EHR-EVALUATION.adverse_reaction_risk.v1]   where     a/name/value='Adverse reaction list'   and a_a/data[at0001]/items[at0002]/value/value like '%peanuts%'`

`  #1.0.0 Invocation exception to method:query:java.lang.IllegalArgumentException: AQL exception:ERROR: bad jsquery representation,  Detail: syntax error, unexpected STRING_P at end of input,  Position: 584`

**Comment by ethercis** [comment]
jsquery does not support like/ilike statement (due to indexing constraints). Will change the where clause building strategy whenever like/ilike is used (will have a -slight- impact on performance).

**Comment by ethercis** [comment]
Posted a new aql-processor library on the test server. Please test. (note your example should read 'ilike' instead of 'like', there is no 'peanut...' but loads of 'Peanut...' in the DB :)

**Comment by ethercis** [comment]
Tested. Thanks!
