### ISSUE TITLE
°C not getting accepted while updating(PUT)

### ISSUE THREAD

**Issue by rubal-jain** [ethercis/ethercis#28]
We have injected an opt for vital signs. The create(POST) is working fine with all the values but the update is giving following error:

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
        <title>Error 400 </title>
    </head>
    <body>
        <h2>HTTP ERROR: 400</h2>
        <p>Problem accessing /rest/v1/composition. Reason:

            <pre>    #1.0.0 Content may be altered found length =2232 expected:2233</pre>
        </p>
        <hr />
        <a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.z-SNAPSHOT</a>
        <hr/>
    </body>
</html>

PFA the vital signs opt
[EHRN Vital signs.txt](https://github.com/ethercis/ethercis/files/1124506/EHRN.Vital.signs.txt)

**Comment by ethercis** [comment]
Could you share the PUT query body please? I will try to reproduce this issue on my side. Thanks

**Comment by rubal-jain** [comment]
{
	  "ctx/composer_name": "Dr Tony Shannon",
      "ctx/health_care_facility|id": "999999-345",
      "ctx/health_care_facility|name": "Ripple View Care Home",
      "ctx/id_namespace": "NHS-UK",
      "ctx/id_scheme": "2.16.840.1.113883.2.1.4.3",
      "ctx/language": "en",
      "ctx/territory": "GB",
      "ctx/time": "2017-07-05T12:08:36+01:00",
      "vital_signs/vital_signs:0/respirations:0/any_event:0/rate|magnitude": "10",
      "vital_signs/vital_signs:0/respirations:0/any_event:0/rate|unit": "/min",
      "vital_signs/vital_signs:0/pulse_heart_beat:0/any_event:0/pulse_rate|magnitude": "100",
      "vital_signs/vital_signs:0/pulse_heart_beat:0/any_event:0/pulse_rate|unit": "/min",
  "vital_signs/vital_signs:0/body_temperature:0/any_event:0/temperature|magnitude": "100.0",
  "vital_signs/vital_signs:0/body_temperature:0/any_event:0/temperature|unit": "°C",
  "vital_signs/vital_signs:0/body_temperature:0/any_event:0/time": "2017-07-05T12:08:36.000+01:00",
  "vital_signs/vital_signs:0/body_temperature:0/site_of_measurement|code": "at0022",
  "vital_signs/vital_signs:0/body_temperature:0/site_of_measurement|value": "Mouth",
  "vital_signs/vital_signs:0/body_temperature:0/site_of_measurement|terminology": "local",
  "vital_signs/vital_signs:0/body_temperature:0/language|code": "en",
  "vital_signs/vital_signs:0/body_temperature:0/language|terminology": "ISO_639-1",
  "vital_signs/vital_signs:0/body_temperature:0/encoding|code": "UTF-8",
  "vital_signs/vital_signs:0/body_temperature:0/encoding|terminology": "IANA_character-sets",
      "vital_signs/vital_signs:0/blood_pressure:0/any_event:0/systolic|magnitude": "120",
      "vital_signs/vital_signs:0/blood_pressure:0/any_event:0/systolic|unit": "mm[Hg]",
      "vital_signs/vital_signs:0/blood_pressure:0/any_event:0/diastolic|magnitude": "80",
      "vital_signs/vital_signs:0/blood_pressure:0/any_event:0/diastolic|unit": "mm[Hg]",
      "vital_signs/vital_signs:0/indirect_oximetry:0/any_event:0/spo2|numerator": "90",
      "vital_signs/vital_signs:0/indirect_oximetry:0/any_event:0/spo2": "9.0",
      "vital_signs/vital_signs:0/clinical_synopsis/synopsis": "high fever",
      "vital_signs/vital_signs:0/clinical_synopsis/language|code": "en"
}

**Comment by ethercis** [comment]
I posted a fix for this issue (had the same issue with POST but was already fixed btw). I have also updated ecis-composition-service-1.1.0-SNAPSHOT with this fix. pls let me know.

**Comment by rubal-jain** [comment]
Thanks Christian, its working as expected now.
