### ISSUE TITLE
Problem commiting with 'table' structure

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#29]
Hi,
I am getting the following error with the attached OPT when trying to create a commit a composition.

>#1.0.0 Invocation exception to method:create:java.lang.IllegalArgumentException: Unhandled data type:at0003, Table

For one of the archetypes in the OPT, we have used 'table' structure instead of 'tree'. What are the data structures supported by Ethercis? Is 'table' supported?

[EHRN Food habits.zip](https://github.com/ethercis/ethercis/files/1134341/EHRN.Food.habits.zip)

**Comment by ethercis** [comment]
As you found out, ITEM_TABLE is not supported (there are no known archetype using it to date). ITEM_SINGLE, ITEM_LIST and ITEM_TREE are supported.

**Comment by freshehr** [comment]
Hi @dileep-ehr, THe clinical modelling community decided some time ago to only use ITEM_TREE, as this allows us maximal flexibility as time goes on. There are a couple of older ITEM_LIST archetypes but these will be updated to ITEM_TREE at some point. I only ever saw one archetype which used TABLE - reflexes but it can easily be remodelled using ITEM_TREE.
