### ISSUE TITLE
How can I export test data from your server?

### ISSUE THREAD

**Issue by ZuzooVn** [ethercis/ethercis#3]
Hi @ethercis 
Thanks for your great work.

Currently, I am using your test server: 178.62.71.220:8080 for the demo purpose.  It works like a champ.
Now I just want to build my local EtherCIS server, how can I export the existing data from your test server and import to my local server?

Thanks and Best Regards,

Nam Vu

**Comment by ethercis** [comment]
Hi,
Since all data are held into the DB, you can simply perform a backup using the Webmin console and restore the data into your local db server. Pls send me an email at: christian _at_ adoc _dot_ co _dot_ ch for instructions.
Thanks -- Christian
