### ISSUE TITLE
Unable to change composer_id & name when updating a composition

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#30]
When I am updating a composition with a different composer_id & name, ethercis seems to be discarding it. The new version has the details from the original composition. However the other archetypes data seems to be getting modified.

**Comment by chevalleyc** [comment]
Are you referring to the contributor id or composer id in composition meta-data?

**Comment by dileep-ehr** [comment]
I am referring to the following in the composition FLAT file
>"encounter/composer|id": "1234-5676",
>"encounter/composer|id_scheme": "userId",
>"encounter/composer|id_namespace": "EHR.NETWORK",
>"encounter/composer|name": "Srinivas",

IMHO, when the same composition is updated by another person, the composer id has to be changed to reflect this. However I am unable to do this.
I am not aware how we can include contributor in the composition metadata.  That would be interesting to find out.

**Comment by dileep-ehr** [comment]
I am still facing this problem. Has anybody else faced this problem? Is the right way to retain the original composer and change contributor with each revision of the composition.

Does Ethercis support contributor in meta-data? If yes can somebody give some details. The example file does not show the syntax for it.

**Comment by tony-shannon** [comment]
closing this for now @dileep-ehr on advice from @chevalleyc, please reopen if any related issues

**Comment by dileep-ehr** [comment]
This problem is not resolved. Tested today and the problem exists still

**Comment by chevalleyc** [comment]
Please post a complete transcript of the operation you try to do (with data sample + template). If the problem cannot be reproduced it will be closed. Thanks

**Comment by dileep-ehr** [comment]
Find attached sample files
- EHRN Family history.v2.opt
- initial commit (composerid- 1234-5678, composer_name-Composer)
- update commit (composerid- 1234-5679, composer_name-Composer1)

But when we retrieve the composition after the update commit, the composer details have not changed as per the updated commit. 





[for_christian.zip](https://github.com/ethercis/ethercis/files/1385622/for_christian.zip)

**Comment by chevalleyc** [comment]
Fixed with CR#67
