### ISSUE TITLE
Configure the namespace in auto-generated composition id

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#31]
Hi,
On making a commit, the composition id is auto generated by the server in the following form.
 >encounter/_uid": "c2da3e4d-6c2c-478d-8c16-32c53c32c8bf::vm01.ethercis.org::3

Can I configure the default namespace (vm01.ethercis.org) to something different (ehr.example.com)? Is there an option to include it in the commit service or FLAT file or do we need to change it on the server?

**Comment by chevalleyc** [comment]
Hi Dileep, I am back from a (too) short break. I will start replying to your CRs. Many thanks -- Christian

**Comment by dileep-ehr** [comment]
Thanks Christian, Hope you had a good break. Wait to hear from you

**Comment by chevalleyc** [comment]
the namespace is set by a jvm environment variable:

<code>-Dserver.node.name=vm01.ethercis.org</code>

You can modify it in the server launch script.

**Comment by dileep-ehr** [comment]
Tested and it works. Thanks.
