### ISSUE TITLE
"/category":"openehr::433|event|",  in ECISFLAT documentation does not seem to be working

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#33]
In [ecisflat](https://github.com/ethercis/ethercis/blob/master/doc/flat%20json.md) documentation, the example includes an option to set the category of the composition
`"/category":"openehr::433|event|"`
Can this be used to set it as a persistent composition ("/category":"openehr::431|persistent|")?
While testing, the composition was accepted, but when I retrieve the composition, this entry is missing in context. Is this functionality currently not implemented? (Ref #23)

**Comment by chevalleyc** [comment]
yes you are right. attribute /category is currently ignored at persistence level.

**Comment by dileep-ehr** [comment]
Is this being considered in the future? If yes, do you have any timeline in mind?

IMHO, now that defining this at the archetype level is being discouraged (refer Ian's comment in #23), it may be a good thing to be able to define some compositions as 'persistent' at creation and build functionality in the application level to use this flag to define specific behaviors such as only allowing one set of persistent compositions per EHR.

**Comment by freshehr** [comment]
Hi both,

I thought I would just pitch in. There are some design issues with the openEHR RM that would make me suggest that you do not make use of category right now. In particular, the current spec says that if a composition is persistent, that it should not carry anything in composition/context. This makes some sense for completely longitudinal persistent records, e.g a patient master problem list but not for other records where we need a persistent commit strategy but only for a period of time, and need context.

My own current practice is to leave all compositions as event and to provide guidance to developers for persistence strategy

see https://www.slideshare.net/ianmcnicoll/openehr-composition-category-persistent-vs-event

Ian

**Comment by dileep-ehr** [comment]
Thanks Ian,
I am just to restate my understanding of what you are recommending to be sure

As there are possible changes to the spec that will have impact on category and it is advisable not to use it in compositions. It is better to handle this as an implementation details during app development as there can be more possibilities than what the current spec allows.

**Comment by freshehr** [comment]
Yes - exactly correct.
