### ISSUE TITLE
AQL across multiple templates does not work

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#35]
I have two opts that contain the encounter composition and separate action archetypes(both specializations of ACTION-service archetype with very similar structure). I am trying to query across compositions from both using the following aql
```
SELECT c/uid/value as uid, c/composer/name as author, c/context/start_time/value as date_created, a_y/ism_transition/careflow_step/definingCode/codeString as ystate_code, a_y/ism_transition/careflow_step/value as ystate, a_y/ism_transition/careflow_step/definingCode/terminologyId/value as ystate_terminology, a_m/ism_transition/careflow_step/definingCode/codeString as mstate_code, a_m/ism_transition/careflow_step/value as mstate, a_m/ism_transition/careflow_step/definingCode/terminologyId/value as mstate_terminology FROM EHR e[ehr_id/value='06a2732f-12af-4ec1-a18f-40aedaab73be'] CONTAINS COMPOSITION c CONTAINS (ACTION a_y[openEHR-EHR-ACTION.service-yoga.v0] OR ACTION a_m[openEHR-EHR-ACTION.service-massage.v0])
WHERE c/name/value='Encounter'
```
It is returning results as below, where the variables does not seem to be getting set properly (for one archetype it is either 'null' or missing.
```
 "uid": "897a8402-0497-4726-98e4-e9f1413892f2::vm01.ethercis.org::3",
            "mstate_terminology": null,
            "null": "local",
            "author": "Dileep",
            "date_created": "2017-07-12T13:30:16+05:30",
            "mstate_code": null,
            "mstate": null
        },
        {
            "uid": "968bf823-29cb-41d6-a57e-967b34380957::vm01.ethercis.org::2",
            "mstate_terminology": "local",
            "null": null,
            "author": "Dileep",
            "date_created": "2017-07-12T13:30:16+05:30",
            "mstate_code": "at0005",
            "mstate": "Service activity complete"
```
Further if I add a new parameter to where as below
```
`WHERE` c/name/value='Encounter' and a_m/ism_transition/careflow_step/value='Service planned'
I get the following error
```
`#1.0.0` Invocation exception to method:query:java.lang.IllegalArgumentException: AQL exception:ERROR: type &quot;jsquery&quot; does not exist,  Position: 2209`

OPTs attached for reference

[opts.zip](https://github.com/ethercis/ethercis/files/1150450/opts.zip)

**Comment by chevalleyc** [comment]
Could you give me examples of POST for these two templates please? Thanks

**Comment by dileep-ehr** [comment]
Find attached. I have added sample commits for the templates in the attched text file
[service_commits.txt](https://github.com/ethercis/ethercis/files/1175465/service_commits.txt)

**Comment by chevalleyc** [comment]
It seems template EHRN Yoga service.v0 is not structured with a content (entry) within a composition, but it's hard to tell without seeing the .oet. Could you check its structure?

**Comment by chevalleyc** [comment]
Further looking at it,  I would recommend to structure the template with SECTION. 
F.e. the field you are looking to use would be addressed likewise to:
<pre><code>a/content[openEHR-EHR-SECTION.referral_details_rcp.v1]/items[openEHR-EHR-ACTION.service.v0]/ism_transition/current_state/value</code></pre>

**Comment by freshehr** [comment]
@dileep-ehr : I would be happy to have a look at the template if you could create a template File export via Template Designer-?File->export. This zips up the .oet and all of the component archetypes.

**Comment by dileep-ehr** [comment]
Thanks Ian for the offer. 
[EHRN Massage service.zip](https://github.com/ethercis/ethercis/files/1182422/EHRN.Massage.service.zip)
[EHRN Yoga service.zip](https://github.com/ethercis/ethercis/files/1182423/EHRN.Yoga.service.zip)

I am attaching the template files for both OPTs. They both use specialized archetypes of 'ACTION.service'. To me they both look the same except for the 'service name', which is both cases are different.

However I have not used SECTION in both these cases. As a matter of curiosity, is it a better practice (or requirement) to use SECTION in all templates?

**Comment by freshehr** [comment]
@dileep-ehr - thanks. I will take a look asap. SECTIONS should (nearly) always be optional. They can help break up large templates from a human perspective, and occasionally helpful to devs but we try very hard not to rely on them for semantics.

**Comment by freshehr** [comment]
@chevalleyc - does Ethercis AQL support wild-card matching on archetype node names to handle specialisation? 

e.g. 

`CONTAINS COMPOSITION c CONTAINS (ACTION a_y[openEHR-EHR-ACTION.service*.v0)`

instead of

`CONTAINS COMPOSITION c CONTAINS (ACTION a_y[openEHR-EHR-ACTION.service-yoga.v0] OR ACTION a_m[openEHR-EHR-ACTION.service-massage.v0])`

**Comment by chevalleyc** [comment]
Wild-card on archetype node name is not yet supported. 

Basically, the CONTAINS clause support is implemented by building a containment index (it's a hierarchical structure projection) which, fortunately, does support wild-cards in its query form. 

For example, a containment record is as follows:

<pre><code>openEHR_EHR_COMPOSITION_encounter_v1.openEHR_EHR_OBSERVATION_blood_pressure_v1</code></pre>

This 'ltree' record can indeed be queried using wild-card and case insensitive search (see postgresql [ltree ](https://www.postgresql.org/docs/9.6/static/ltree.html)doc).

The containment index is used in turn to resolve path expression for a symbol (example: a_y above).

Since this CR is associated to containment and requires some fix, I will prepare the change to support this as well.

**Comment by chevalleyc** [comment]
I've posted a new aql library giving the correct results I think:
<pre><code>
        {
            "uid": "0b1a8549-6a11-40b2-a988-3a9f23173b82::local.ethercis.com::1",
            "mstate_terminology": null,
            "ystate_code": "at0002",
            "author": "Dileep",
            "date_created": "2017-07-12T23:23:16+05:30",
            "ystate": "Service planned",
            "ystate_terminology": "local",
            "mstate_code": null,
            "mstate": null
        },
        {
            "uid": "0ba8a16a-29d9-4e0b-b4db-f3142bd2feb7::local.ethercis.com::1",
            "mstate_terminology": "local",
            "ystate_code": null,
            "author": "Dileep",
            "date_created": "2017-07-12T23:23:16+05:30",
            "ystate": null,
            "ystate_terminology": null,
            "mstate_code": "at0002",
            "mstate": "Service planned"
        },
        {
            "uid": "1afc43d7-d610-46cb-8468-83dba1bdf2fa::local.ethercis.com::1",
            "mstate_terminology": null,
            "ystate_code": "at0002",
            "author": "Dileep",
            "date_created": "2017-07-12T23:23:16+05:30",
            "ystate": "Service planned",
            "ystate_terminology": "local",
            "mstate_code": null,
            "mstate": null
        },
        {
            "uid": "685194a1-2fe8-4058-b814-16f818e4fbaa::local.ethercis.com::1",
            "mstate_terminology": null,
            "ystate_code": "at0002",
            "author": "Dileep",
            "date_created": "2017-07-12T23:23:16+05:30",
            "ystate": "Service planned",
            "ystate_terminology": "local",
            "mstate_code": null,
            "mstate": null
        }
</code></pre>

**Comment by dileep-ehr** [comment]
Continued on issue #40 and closed
