### ISSUE TITLE
ADMIN entry OPT returns NULL for template example 

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#37]
I have two opts that contain ADMIN entry archetypes. While 'adding template' they return success. But when I try to get example files, the server returns NULL.

[EHRN Admit interview.zip](https://github.com/ethercis/ethercis/files/1176243/EHRN.Admit.interview.zip)

**Comment by chevalleyc** [comment]
found an issue with generating an example when context is null. Fixed.

**Comment by dileep-ehr** [comment]
Tested working. Thanks
