### ISSUE TITLE
AQL resultset format for objects not pulling data back correctly.

### ISSUE THREAD

**Issue by freshehr** [ethercis/ethercis#38]
Hi all. The problem here is not the AQL. I am pretty sure that the issue is that the 'raw' openEHR json coming back from Ethercis is not quite correct. @

The comment that is messing Rob up is actually associated with an individual result, not with the whole panel (though there can be a separate element for that, which we do use at times). The problem is that there is a chunk of json essentially missing. I did try to explain that in the other thread.

This
```
[{
"name": {
"value": "Laboratory result"
},
"items": [{
"name": {
"value": "Comment"
},
"value": {
"value": "singificantly raised level"
},
"@Class": "DV_TEXT",
"archetype_node_id": "at0003"
}],
"archetype_node_id": "at0002"
},
```

should be 

```
"items": [
        {
                                "name": {
                                    "@class": "DV_CODED_TEXT",
                                    "value": "Total HDL",
                                    "defining_code": {
                                        "@class": "CODE_PHRASE",
                                        "terminology_id": {
                                            "@class": "TERMINOLOGY_ID",
                                            "value": "SNOMED-CT"
                                        },
                                        "code_string": "71006"
                                    }
                                },
                                "archetype_node_id": "at0001",
                                "value": {
                                    "@class": "DV_QUANTITY",
                                    "normal_range": {
                                        "@class": "DV_INTERVAL",
                                        "lower": {
                                            "@class": "DV_QUANTITY",
                                            "magnitude": 80,
                                            "units": "mmol/l"
                                        },
                                        "upper": {
                                            "@class": "DV_QUANTITY",
                                            "magnitude": 110,
                                            "units": "mmol/l"
                                        },
                                        "lower_unbounded": false,
                                        "upper_unbounded": false
                                    },
                                    "magnitude": 123,
                                    "units": "mmol/l",                                        
                                }
                            },
                            {
                              "archetype_node_id": "at0003",
                              "name": {
                                "value": "Comment"
                                },
                              "value": {
                                "value": "singificantly raised level"
                              }
                            }
                        ]
``` 

See https://github.com/RippleOSI/Ripple-openEHR/issues/8#issuecomment-312304163 for full discussion.

**Comment by chevalleyc** [comment]
I have fixed most of these issues and now the formatting is:

<pre><code>
{
            "conclusion": "Rapidly deteriorating renal function",
            "uid": "1d27906b-ebc7-4848-9f1b-73187ee4f72e::vm01.ethercis.org::1",
            "test_panel": {
                "name": {
                    "value": "Laboratory test panel"
                },
                "items": [
                    {
                        "archetype_node_id": "at0002",
                        "name": {
                            "value": "Laboratory result"
                        },
                        "items": [
                            {
                                "name": {
                                    "value": "Urea"
                                },
                                "value": {
                                    "units": "mmol/l",
                                    "accuracy": 0,
                                    "magnitude": 7.4,
                                    "precision": 0,
                                    "normal_range": {
                                        "interval": {
                                            "lower": {
                                                "units": "mmol/l",
                                                "accuracy": 0,
                                                "magnitude": 2.5,
                                                "precision": 0,
                                                "accuracy_percent": false
                                            },
                                            "upper": {
                                                "units": "mmol/l",
                                                "accuracy": 0,
                                                "magnitude": 6.6,
                                                "precision": 0,
                                                "accuracy_percent": false
                                            },
                                            "lower_included": true,
                                            "upper_included": true
                                        }
                                    },
                                    "accuracy_percent": false
                                },
                                "@class": "DV_QUANTITY",
                                "archetype_node_id": "at0001"
                            },
                            {
                                "name": {
                                    "value": "Comment"
                                },
                                "value": {
                                    "value": "may be technical artefact"
                                },
                                "@class": "DV_TEXT",
                                "archetype_node_id": "at0003"
                            }
                        ]
                    },
                    {
                        "archetype_node_id": "at0002",
                        "name": {
                            "value": "Laboratory result #2"
                        },
</code></pre>

Please test. Thanks

**Comment by chevalleyc** [comment]
NB. the zeroed or null values f.e. optional attributes in DV_QUANTITY are still there as it is a separate issue. This is somewhat a cosmetic change in the DB encoding. Could be done during an optimization phase.

**Comment by freshehr** [comment]
Thanks CC!!

Can we add the archetype_node_id at root archetype level as this will make it easier to navigate and further process the structure
e.g.
```
 "conclusion": "Rapidly deteriorating renal function",
            "uid": "1d27906b-ebc7-4848-9f1b-73187ee4f72e::vm01.ethercis.org::1",
            "test_panel": {
                 
                    "value": "Laboratory test panel"
                },
"conclusion": "Rapidly deteriorating renal function",
            "uid": "1d27906b-ebc7-4848-9f1b-73187ee4f72e::vm01.ethercis.org::1",
            "test_panel": {
                "name": {
                    "value": "Laboratory test panel"
                },
             "archetype_node_id": "openEHR-EHR-CLUSTER.laboratory_panel.v0",
              "items": [
                    {
                        "archetype_node_id": "at0002",
                        "name": {
                            "value": "Laboratory result"
                        },
                        "items": [
```

**Comment by chevalleyc** [comment]
New version uploaded with root archetype node id and correct name/value encoding

**Comment by chevalleyc** [comment]
Example:
<pre><code>
    "resultSet": [
        {
            "conclusion": "result within expected range",
            "uid": "32f96f05-16c2-414c-8fa7-5df211946c9f::vm01.ethercis.org::1",
            "test_panel": {
                "name": {
                    "value": "Laboratory test panel"
                },
                "items": [
                    {
                        "archetype_node_id": "at0002",
                        "name": {
                            "value": "Laboratory result"
                        },
                        "items": [
                            {
                                "name": {
                                    "value": "white blood cell count"
                                },
                                "value": {
                                    "units": "10*9/l",
                                    "accuracy": 0,
                                    "magnitude": 4.7,
                                    "precision": 0,
....
</code></pre>

**Comment by chevalleyc** [comment]
Uploaded a new version with root archetype node id and correct name/value json encoding:

<pre><code>
    "resultSet": [
        {
            "conclusion": "result within expected range",
            "uid": "32f96f05-16c2-414c-8fa7-5df211946c9f::vm01.ethercis.org::1",
            "test_panel": {
                "archetype_node_id": "openEHR-EHR-CLUSTER.laboratory_test_panel.v0",
                "name": {
                    "value": "Laboratory test panel"
                },
                "items": [
                    {
                        "archetype_node_id": "at0002",
                        "name": {
                            "value": "Laboratory result"
                        },
                        "items": [
                            {
                                "name": {
                                    "value": "white blood cell count"
                                },
                                "value": {
                                    "units": "10*9/l",
   
</code></pre>

**Comment by chevalleyc** [comment]
Note to self: this transformation should be implemented at DB level (PL/SQL) as it is rather costly when performed at middleware level.

**Comment by tony-shannon** [comment]
closing this Ian @freshehr , please reopen if any related issues
