### ISSUE TITLE
AQL object resultset format tweaks?

### ISSUE THREAD

**Issue by freshehr** [ethercis/ethercis#39]
I'm happy enough with the slightly simplified version of canonical JSON that Ethercis is returning from AQL for objects but would suggest some tweaks.

1. I would suggest that ALL archetype node Ids are returned - it looks as if some ? all root archetype NodeId attributes are being omitted. This will make further downstream parsing tricky and makes it hard ot navigate complex structures.

2. All attribute names should match the RM name exactly e.g, in DV_quantity.

"normalRange" should be normal_range
"accuracyPercent" should be accuracy_percent,
"magnitudeStatus" should be magnitude_status

3. some of the optional dv_quantity attributes could be omitted if empty

e.g.
accuracy
accuracy_percent:
magnitude_status
normal_status

**Comment by chevalleyc** [comment]
Please see CR#38

**Comment by tony-shannon** [comment]
see https://github.com/ethercis/ethercis/issues/38
closing this Ian @freshehr , please reopen if any related issues
