### ISSUE TITLE
AQL exception when querying on multiple templates

### ISSUE THREAD

**Issue by linto17** [ethercis/ethercis#40]
Error:
#1.0.0 Invocation exception to method:query:java.lang.IllegalArgumentException: AQL exception:ERROR: UNION types character varying and numeric cannot be matched,  Position: 2771

Query:
select
    c/uid/value as uid,
    c/composer/name as author,
    c/context/start_time/value as date_created, 
    y/description[at0001]/items[at0.31]/value/magnitude as ydur,
    m/description[at0001]/items[at0.31]/value/magnitude as mdur
    from EHR e [ehr_id/value = '{{ehrId}}'] 
contains COMPOSITION c 
contains (ACTION y[openEHR-EHR-ACTION.service-yoga.v0] or ACTION m[openEHR-EHR-ACTION.service-massage.v0])
 where c/name/value='Encounter'

It works when I use only one ACTION in the query.
Please help, Thanks in advance.

**Comment by chevalleyc** [comment]
Fixed (issue was missing explicit typecast on null column, defaulted to TEXT by pgsql). Library updated.

**Comment by linto17** [comment]
Thanks
