### ISSUE TITLE
aql query with multiple ehr id's

### ISSUE THREAD

**Issue by shafeef** [ethercis/ethercis#41]
hi,

is it possible to write a aql query with multiple ehr id's..

like this:-

{{serverURL}}/rest/v1/query?aql=select TOP 1 
    a/uid/value as uid,
    a/composer/name as author,
    a/context/start_time/value as date_created,
    b_b/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitude as height,
    b_c/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude as weight,
    b_d/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitude as bmi, b_e/data[at0001]/items[at0003]/value/value as status from EHR e **# [ehr_id/value = 'a1153dd5-ec36-44e9-9823-0e3dec07a8df' and 'a1153dd5-hfrjjf-44e9-9823-jfhfskjfdrurr ']**
    contains COMPOSITION a[openEHR-EHR-COMPOSITION.encounter.v1]
    contains (
    OBSERVATION b_b[openEHR-EHR-OBSERVATION.height.v1] or
    OBSERVATION b_c[openEHR-EHR-OBSERVATION.body_weight.v1] or
    OBSERVATION b_d[openEHR-EHR-OBSERVATION.body_mass_index.v1] or OBSERVATION b_e[openEHR-EHR-EVALUATION.child_nutrition_status.v0]) ORDER BY date_created asc

**Comment by chevalleyc** [comment]
It is not supported. Right now, the grammar only supports a single ehr_id/value selection.

**Comment by shafeef** [comment]
okay, thank you so much.
