### ISSUE TITLE
Composition commit fails // FLAT JSON related

### ISSUE THREAD

**Issue by freshehr** [ethercis/ethercis#42]
The following composition commit returns an error - nothing clearly incorrect and it commits fine on Think!Ehr.

Problem accessing /rest/v1/composition. Reason:

    #1.0.0 Invocation exception to method:create:java.lang.IllegalArgumentException: Could not convert JSON map:java.lang.ClassCastException: class com.marand.thinkehr.f.a.b.k not an enum

```
POST /rest/v1/composition?ehrId=c42b6a28-67ae-4bb6-b446-b2328b054fe9&amp;templateId=Smart Growth Chart Data.v0&amp;committerName=Dr Franke&amp;format=FLAT HTTP/1.1
Host: 178.62.71.220:8080
Authorization: Basic Z3Vlc3Q6Z3Vlc3Q=
Ehr-Session: sessionId:127.0.0.1-guest-1501795290030--287002854-744
Content-Type: application/json

{
  "ctx/composer_name": "Dr Tony Shannon",
  "ctx/health_care_facility|id": "999999-345",
  "ctx/health_care_facility|name": "Home",
  "ctx/id_namespace": "NHS-UK",
  "ctx/id_scheme": "2.16.840.1.113883.2.1.4.3",
  "ctx/language": "en",
  "ctx/territory": "GB",
  "ctx/time": "2017-03-24T00:11:02.518+02:00",
    "smart_growth_report/body_weight/weight|magnitude": 12.7,
    "smart_growth_report/body_weight/weight|unit": "kg",
    "smart_growth_report/height_length/any_event:0/height_length|magnitude": 90.09,
    "smart_growth_report/height_length/any_event:0/height_length|unit": "cm",
    "smart_growth_report/head_circumference/any_event:0/head_circumference|magnitude": 52,
    "smart_growth_report/head_circumference/any_event:0/head_circumference|unit": "cm"
}

```

**Comment by chevalleyc** [comment]
Just tested it out this morning. I think it's a problem with Marand's library (cannot debug it as it is closed source)

**Comment by chevalleyc** [comment]
Sent an email to Bostjan about this issue.

**Comment by chevalleyc** [comment]
Marand's FLAT json support issue. Will be discussed during the EtherCIS meeting in December as to whether or not keeping supporting a closed source piece of code in EtherCIS.

**Comment by freshehr** [comment]
For information, this occurs if the is any constraint on a DV_DURATION datatype tp restrict the time periods e.g allowing days only, and it occurs if the constraint is set anywhere in the template or in an underlying archetype, even if the data instance being validated does not contain data for that Duration element. If the time units constraint can be removed, the composition commits correctly.
