### ISSUE TITLE
Aql query returns error

### ISSUE THREAD

**Issue by shafeef** [ethercis/ethercis#43]
The following Aql query returns an error:

Error:

Problem accessing /ehr/rest/v1/query. Reason:

    #1.0.0 Invocation exception to method:query:java.lang.IllegalArgumentException: AQL exception:ERROR: type "jsquery" does not exist,  Position: 2202

AQL query:

rest/v1/query?aql=select   a/uid/value as uid,
    a/composer/name as author,
    a/context/start_time/value as date_created,
    b_b/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitude as height,
    b_c/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude as weight,
    b_d/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitude as bmi, b_e/data[at0001]/items[at0003]/value/value as status from EHR e [ehr_id/value = '8645bfc3-08a2-4465-98d7-10f73c81fd94']
    contains COMPOSITION a[openEHR-EHR-COMPOSITION.encounter.v1]
    contains (
    OBSERVATION b_b[openEHR-EHR-OBSERVATION.height.v1] or
    OBSERVATION b_c[openEHR-EHR-OBSERVATION.body_weight.v1] or
    OBSERVATION b_d[openEHR-EHR-OBSERVATION.body_mass_index.v1] or OBSERVATION b_e[openEHR-EHR-EVALUATION.child_nutrition_status.v0]) **where b_e/data[at0001]/items[at0003]/value/value = 'Normal'**  ORDER BY date_created asc

**Comment by shafeef** [comment]
When i use 'LIKE' instead of '=' it's giving me proper response

here is the query

rest/v1/query?aql=select   a/uid/value as uid,
    a/composer/name as author,
    a/context/start_time/value as date_created,
    b_b/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitude as height,
    b_c/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude as weight,
    b_d/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitude as bmi, b_e/data[at0001]/items[at0003]/value/value as status from EHR e [ehr_id/value = '8645bfc3-08a2-4465-98d7-10f73c81fd94']
    contains COMPOSITION a[openEHR-EHR-COMPOSITION.encounter.v1]
    contains (
    OBSERVATION b_b[openEHR-EHR-OBSERVATION.height.v1] or
    OBSERVATION b_c[openEHR-EHR-OBSERVATION.body_weight.v1] or
    OBSERVATION b_d[openEHR-EHR-OBSERVATION.body_mass_index.v1] or OBSERVATION b_e[openEHR-EHR-EVALUATION.child_nutrition_status.v0]) where b_e/data[at0001]/items[at0003]/value/value like 'Normal'  ORDER BY date_created asc

**Comment by chevalleyc** [comment]
Could you make sure extension 'jsquery' is installed and visible to DB ethercis? AQL uses an explicit typecast in the form '::jsquery' when using the equal operator. If this extension is missing, the query fails.

**Comment by shafeef** [comment]
yea, just now i have added 'jsquery' extension in pgsql_ehr.ddl file and restarted the ethercis, but same error

**Comment by chevalleyc** [comment]
Extension jsquery must be created at db level. To figure out your db extensions, you can run the following commands from within PGADMIN (make sure db ethercis is selected when you open an SQL query windows):

<pre><code>SELECT * FROM pg_available_extensions</code></pre>

You should find a record as follows:

"jsquery";"1.0";"1.0";"data type for jsonb inspection"

NB. modifying pgsql_ehr.ddl doesn't have any impact on a running DB. Likewise, EtherCIS does not modify/alter the DB.

**Comment by shafeef** [comment]
okay thank you, i'm searching for jsquery extension now...

**Comment by dileep-ehr** [comment]
Installed jsquery from source and added to ethercis database. Equality and numeric operators seem to be working now. But some of the operators like type and existence returns error. Do you have a list of jsquery operators that Ethercis supports currently?

For example to eliminate sets with null value, I tried using the existence (= *). But am getting token recognition error

**Comment by chevalleyc** [comment]
Are you using AQL? Could you please post your query so I can have a look. Thanks
NB. only AQL operators are supported, if you want to use specialized jsquery operator, you have to use direct SQL query instead.

**Comment by dileep-ehr** [comment]
I have tested with AQL. All basic operators except '!=' are working. '!=' returns the following error

`#1.0.0 Invocation exception to method:query:java.lang.IllegalArgumentException: AQL exception:ERROR: bad jsquery representation,  Detail: syntax error, unexpected $undefined at or near &quot;!&quot;,  Position: 2807`

However I found a work around using the 'NOT' before the equality as below
`where c/name/value='Service tracker'AND NOT b_a/items[at0001]/value/magnitude = 5 `

Another problem that I am facing is to filter out compositions with 'null' values. No combination of operators that I tried seems to work. Any ideas?

**Comment by freshehr** [comment]
Can you post an example of a composition with nulls? - I'm not exactly sure what you mean. Normally it should not be possible to store empty elements unless they are specifically set to null.

**Comment by dileep-ehr** [comment]
I realized that the problem is not with compositions having nulls. It is aql returning null when the item does not exist in the composition. What I want is aql to return only compositions only if a specified path exists. Please see example below

I am running this aql
```
select
    c/uid/value as uid,
    c/composer/name as author,
    w/description[at0001]/items[at0011]/value/value as service,
    w/description[at0001]/items[at0.32]/value/value as endTime,
    w/ism_transition/current_state/value as currentState,
    c/context/start_time/value as date_created,
    b_a/items[at0001]/value/magnitude as rating,
    b_a/items[at0002]/value/value as feedback,
    b_a/items[at0003]/value/value as improvement
    from EHR e [ehr_id/value = '{{ehrId}}']
    contains COMPOSITION c[openEHR-EHR-COMPOSITION.service_tracker.v0]
    contains ACTION w[openEHR-EHR-ACTION.service-wellness.v0]
    contains CLUSTER b_a[openEHR-EHR-CLUSTER.feedback.v0]
```
To return this result set
   ```
{
            "feedback": "DEFAULT_TEXT_VALUE",
            "uid": "023c2e93-6f9c-4b76-bbc2-f77a19fbb87c::vm01.ethercis.org::1",
            "author": "Composer",
            "service": "Massage",
            "date_created": "2017-08-18T13:50:59+05:30",
            "rating": "0",
            "endTime": "1900-01-01T00:00:00.000Z",
            "currentState": "planned",
            "improvement": "DEFAULT_TEXT_VALUE"
        },
        {
            "feedback": null,
            "uid": "072f65c7-06ee-48ab-8094-96263f446ea0::vm01.ethercis.org::1",
            "author": "Bob Smith",
            "service": "Massage",
            "date_created": "2017-08-18T15:03:59+01:00",
            "rating": null,
            "endTime": null,
            "currentState": "planned",
            "improvement": null
        },
```
As you can see the second set has rating value null, which means that "b_a/items[at0001]/value/magnitude" does not exist in that composition. What I want is the aql to return only sets where "b_a/items[at0001]/value/magnitude" exists. So I try this
```
select
    c/uid/value as uid,
    c/composer/name as author,
    w/description[at0001]/items[at0011]/value/value as service,
    w/description[at0001]/items[at0.32]/value/value as endTime,
    w/ism_transition/current_state/value as currentState,
    c/context/start_time/value as date_created,
    b_a/items[at0001]/value/magnitude as rating,
    b_a/items[at0002]/value/value as feedback,
    b_a/items[at0003]/value/value as improvement
    from EHR e [ehr_id/value = '{{ehrId}}']
    contains COMPOSITION c[openEHR-EHR-COMPOSITION.service_tracker.v0]
    contains ACTION w[openEHR-EHR-ACTION.service-wellness.v0]
    contains CLUSTER b_a[openEHR-EHR-CLUSTER.feedback.v0]
    where exists b_a/items[at0001]/value/magnitude
```
and I get this error
`            <pre>    #1.0.0 Invocation exception to method:query:java.lang.NullPointerException</pre>
`
I try this aql
```
select
    c/uid/value as uid,
    c/composer/name as author,
    w/description[at0001]/items[at0011]/value/value as service,
    w/description[at0001]/items[at0.32]/value/value as endTime,
    w/ism_transition/current_state/value as currentState,
    c/context/start_time/value as date_created,
    b_a/items[at0001]/value/magnitude as rating,
    b_a/items[at0002]/value/value as feedback,
    b_a/items[at0003]/value/value as improvement
    from EHR e [ehr_id/value = '{{ehrId}}']
    contains COMPOSITION c[openEHR-EHR-COMPOSITION.service_tracker.v0]
    contains ACTION w[openEHR-EHR-ACTION.service-wellness.v0]
    contains CLUSTER b_a[openEHR-EHR-CLUSTER.feedback.v0]
    where c/name/value='Service tracker'AND EXISTS b_a/items[at0001]/value/magnitude
```
and I get this error
`<pre>    #1.0.0 Invocation exception to method:query:java.lang.IllegalArgumentException: AQL exception:ERROR: syntax error at or near &quot;EXISTS&quot;,  Position: 2775</pre>`

I am unable to get the 'exists' operator to work. Can you give me the correct way to use it?

**Comment by chevalleyc** [comment]
EXISTS is not supported yet. It is defined in the ANTLR grammar, but no logic is associated with it.

**Comment by freshehr** [comment]
EXISTS is defined in the AQL spec - definitely worth implementing.

https://openehr.atlassian.net/wiki/spaces/spec/pages/4915244/Archetype+Query+Language+Description#ArchetypeQueryLanguageDescription-AQLSyntaxDescription

**Comment by chevalleyc** [comment]
Added EXISTS in roadmap. Thanks
