### ISSUE TITLE
REST API link is broken

### ISSUE THREAD

**Issue by al-indigo** [ethercis/ethercis#44]
The link provided in the Readme.md (docs/rest api.md) leads nowhere (https://code-4-health.org/platform/open_interfaces_apis/ehrscape/ehrscape_api_reference)

Could you provide please available REST API docs?

**Comment by dileep-ehr** [comment]
Try this. 
https://www.ehrscape.com/reference.html#_electronic_health_record_apis

**Comment by tony-shannon** [comment]
closing this @al-indigo , please reopen if any related issues
