### ISSUE TITLE
Gradle build failing

### ISSUE THREAD

**Issue by dmcollie** [ethercis/ethercis#45]
I'm building an Ansible playbook to install ehrservice on a vagrant image. When running 'gradle build' I'm running into problems with the error 'package com.ethercis.aql.parser does not exist'. It looks like this package should be generated by antlr. Is this something that needs to be done outside of the gradle build?

**Comment by dngferreira** [comment]
Hi, I also have this problem and can't seem to figure it out.
I can see the files generated but the gradle build can't find them. 
Are we missing something?

**Comment by chevalleyc** [comment]
I will get on this issue whenever possible, in the meantime you can use Maven to build aql-processor.

**Comment by chevalleyc** [comment]
We have decided to focus on Maven for the time being (v1.1.2).
