### ISSUE TITLE
How are 'encounter' and 'episode' handled in Ethercis?

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#48]
Hi,
Are the concepts of 'encounter' and 'episode' available in Ethercis? If not, what is the best way to handle them during implementation?

I am experimenting with an admin composition with admit/discharge dates to define an episode and use those dates to identify the compositions that happen within that episode. But I am not sure if that is the most elegant approach. 

The above approach also does not handle encounter, especially since an encounter may have more than one composition and so the commit date cannot be used.

**Comment by freshehr** [comment]
Hi Dileep,

Can you define more clearly what you mean by Encounter and Episode as these phrases are used somewhat variably?
 
An Encounter in openEHR is really defined by the Encounter archetype to be some sort of point-in-time interaction between patient and heathcare worker - a consultation, a vital signs measurement etc,

There are no specific definitions of Episode of Care in openEHR . I am aware of 2 approaches to 'grouping' Encounters and other compositions that relate to the same episode of illness, care pathway etc'.

1.  Add an admin_enry or cluster archetype to composition/other_context to carry episode of care identifiers, other metadata.

2. Use openEHR folders to group those compositions - this is how Code24 manage mental healthcare episodes. They have a persistent composition that handles the metadata for each episode.

Ian

**Comment by dileep-ehr** [comment]
Hi Ian,
My understanding of encounter is similar to what you mention. However, what I am confused about is if we have multiple compositions getting created for a clinical interaction such as an OP visit (consult, vital signs measurements, lab results etc), will they all fall under the same encounter? If yes what context parameters do we use to record that all of them happened in an encounter?

My understanding of episode is also of a group of encounters that have some common clinical significance. In our use case the entire duration of a wellness therapy (1-3 weeks) is treated as an episode. We plan to use the check in and check out dates in the admit composition to define the duration of the episode and filter all the compositions that happen in that episode.

My understanding is that Ethercis treats compositions as independent pieces of clinical information and leaves the concept of episode and encounter for the implementation to manage. Personally I feel that an EHR server should, at least, include the concept of encounter and the ability to link multiple compositions to it.  If it is felt that episode is not universally understood in the same way, it can be left as an implementation detail for now.

**Comment by freshehr** [comment]
Hi Dileep,

openEHR does not have concepts of 'episode of care' / 'period of care' so this is not a limitation per-se
One approach is simply to create a little cluster archetype that plugs into composition/other_context to handle episode metadata like EpisodeID, Encounter IDmanaging organisation. to tie together compositions in whichever way suite your use-case.

The alternative is to use openEHR FOLDERS. I know this is extensively used by some openEHR vendors e.g to manage care planning for mental health. All related compositions are placed in a FOLDER along with a persistent composition containing an admin_entry that manages the 'episode / care planning metadata'.

I would probably go down that route but I'm not sure if EtherCis supports FOLDERs yet.

http://www.openehr.org/releases/RM/latest/docs/common/common.html#_directory_package

**Comment by dileep-ehr** [comment]
Dear Ian,

Ethercis may not need to support Episode as it is not an OpenEHR concept. Is that the same for encounter as well? I was under the impression that OpenEHR does have the concept of encounter. 

If that is the case, will it not be good for Ethercis to support it natively?

**Comment by freshehr** [comment]
Hi Dileep,

There is an Encounter composition archetype but that covers the idea of a consultation or other direct interaction with e patient. Your definition of Encounter might include several such 'consultations' at the same organisation on the same day (I think), but related to one set of health issues.

openEHR does not carry anything that directly supports that, or indeed a set of such interactions across a longer period. In part this is because this varies considerably depending on the healthcare system but is easy enough to add the requisite metadata to compositions to give the correct result. 

Myt suggestion above still stands


1. The quick and easy solution is just to label the related compositions with some sort of EncounerId or EpisodeId

2. openEHR Folders - but that would need support from Ethercis.

**Comment by dileep-ehr** [comment]
Dear Ian,

I am fully in sync with what you are suggesting. Adding an
encounterid/episodeid to encounter composition would be a good way to link
compositions to any particular clinical encounter. However, the concern is
regarding the generation and management of these IDs. Shouldn't that be
managed by the EHR server, just as it manages the compositionis, EHRid etc.

Given that currently Ethercis does not do this, will it be appropriate to
create admin compositions to define episodes and encounters and use their
composition id as encounterid and episodeid in encounter compositions?

regards

Dileep V S
*Founder*
HealtheLife Ventures LLP
m: +91 9632888113
a: 103, Innovation Centre, IIIT, Electronics City, Bangalore 560100
w: healthelife.in  e: dileep@healthelife.in

**Comment by freshehr** [comment]
yup - that would work.  I'd still like to see Folders in EtherCis as I think they will become very useful for handling care planning.
