### ISSUE TITLE
Format for 'Duration' data type

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#49]
The section in OpenEHR specs for Duration data type defines it as an Iso8601_duration string (http://www.openehr.org/releases/RM/latest/docs/data_types/data_types.html#_dv_duration_class). So this data type should allow string.

However the example file returns it as "PT0S". I am able to commit with "PT20S" to denote 20 seconds. What is the syntax for representing years, months, weeks etc

**Comment by freshehr** [comment]
Hi Dileep,

https://en.wikipedia.org/wiki/ISO_8601#Durations

**Comment by dileep-ehr** [comment]
Thanks Ian

Dileep V S
Founder
HealtheLife Ventures LLP
+91 9632888113
103, Innovation Centre, IIIT, Electronics City, Bangalore 560100,
healthelife.in
