### ISSUE TITLE
Querying SELECT OFFSET-FETCH

### ISSUE THREAD

**Issue by maxcda101** [ethercis/ethercis#5]
Hi @ethercis 
I have been trying to testing a little bit about how to implement custom paging in AQL, when I call `/rest/v1/query` with this body,

> {"aql":" select  a/uid/value as uid,     a/composer/name as author,     a/context/start_time/value as date_created,     b_a/items[at0057]/value/value as onAir,
> b_b/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitude as respiratoryRate,     b_c/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude as heartRate,     b_d/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude as temperature,     b_f/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/defining_code/code_string as levelOfConsciousnessCode,     b_g/data[at0001]/events[at0006]/data[at0003]/items[at0004]/value/magnitude as systolic,
>    b_g/data[at0001]/events[at0006]/data[at0003]/items[at0005]/value/magnitude as diastolic,     b_h/data[at0001]/events[at0002]/data[at0003]/items[at0006]/value/numerator as oxygenSats,     b_i/data[at0001]/events[at0002]/data[at0003]/items[at0028]/value/magnitude as newsScore from EHR e [ehr_id/value = '2bb82a07-d529-45df-bc8b-b9fc52b8e1f5'] contains COMPOSITION a[openEHR-EHR-COMPOSITION.encounter.v1] contains (     CLUSTER b_a[openEHR-EHR-CLUSTER.ambient_oxygen.v0] or     OBSERVATION b_b[openEHR-EHR-OBSERVATION.respiration.v1] or     OBSERVATION b_c[openEHR-EHR-OBSERVATION.pulse.v1] or     OBSERVATION b_d[openEHR-EHR-OBSERVATION.body_temperature.v1] or     OBSERVATION b_f[openEHR-EHR-OBSERVATION.avpu.v1] or     OBSERVATION b_g[openEHR-EHR-OBSERVATION.blood_pressure.v1] or     OBSERVATION b_h[openEHR-EHR-OBSERVATION.indirect_oximetry.v1] or     OBSERVATION b_i[openEHR-EHR-OBSERVATION.news_uk_rcp.v1])  where a/name/value='Vital Signs Observations'
>    ORDER BY date_created DESC offset 10 rows
> FETCH NEXT 10 rows only
>    "}

I added `ORDER BY date_created DESC offset 10 rows FETCH NEXT 10 rows only`, Purpose is to  querying filters rows 10 through 10, but not working.

Can you help me with this problem?
Thanks
Quan from ThinkLabs-VN

**Comment by ethercis** [comment]
Hi Quan
AQL FETCH NEXT, OFFSET are not yet supported by EtherCIS. A possible workaround would be to use a direct SQL query instead.
Thanks -- Christian

**Comment by maxcda101** [comment]
Can you help me convert this AQL to SQL query ? Because I don't know much about aql query.

**Comment by ethercis** [comment]
Basically, you can add the 'explain' parameter when you post your query:

`/rest/v1/query?explain=true`

This will return one or more SQL subqueries. If you have a list, you can join then using UNION.

**Comment by maxcda101** [comment]
Thank you, I have successfully implemented
