### ISSUE TITLE
AQL select parameter for composition version

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#52]
Is there any direct select parameter to get the composition version in AQL? 

'a/uid/value as uid' gives the full composition ID including version. Is there something like 'a/uid/version/value as version' to get the version directly?

**Comment by chevalleyc** [comment]
You can use functions in AQL expressions (Warning: it is not *yet* standardized). The list of functions are described in [aql-processor readme](https://github.com/ethercis/ehrservice/blob/remote-github/aql-processor/README.md#function-supportl).

In your scenario, you could f.e. use:

``` 
select   
    split_part(a/uid/value, '::', 1) as uid,
    split_part(a/uid/value, '::', 3) as compo_version,   
  initcap(a/composer/name)  as author,
  a/context/start_time/value as date_created  from EHR e 
  contains COMPOSITION a[openEHR-EHR-COMPOSITION.report-result.v1]
  contains OBSERVATION a_a[openEHR-EHR-OBSERVATION.laboratory_test.v0]  
  where a/name/value='Laboratory test report'
```
You get something like:
```
        {
            "uid": "a601a3df-cfea-4cb8-9b82-5737522b52c4",
            "author": "Dr Lab",
            "date_created": "2015-04-15T06:11:02+02:00",
            "compo_version": "1"
        },
```
There are many other possibilities though, need some testing ;)

**Comment by chevalleyc** [comment]
NB. Please update your libraries!

**Comment by dileep-ehr** [comment]
Thanks Christian.
