### ISSUE TITLE
EtherCIS server stops issuing Sessions

### ISSUE THREAD

**Issue by robtweed** [ethercis/ethercis#53]
Today the EtherCIS server used by the Ripple stack began refusing to start new Sessions, presumably because it was being overwhelmed by demand due to new development work.

After some time it began issuing Sessions again.

Ripple now caches and re-uses OpenEHR sessions as much as possible, but we do still appear to be hitting the limits of the EtherCIS system

Is there anything that can be done to alleviate this situation at the EtherCIS end?

Rob

**Comment by chevalleyc** [comment]
There are different ways to extend the number of active sessions per user as well as the timeout value.

You can tweak your user session by setting up session parameters in the HTTP header (see attached document).

[http-headers.pdf](https://github.com/ethercis/ethercis/files/1362012/http-headers.pdf)

Another possibility is to change the defaults in /etc/opt/ecis/services.properties:
```
#session parameters
session.timeout=1800000
session.maxSessions=20
session.clearSessions=false
session.reconnectSameClientOnly=true
```
But this requires restarting the server on the test server. This can be also tuned via JMX.

**Comment by robtweed** [comment]
Thanks Christian - so I can add a header to an HTTP request:

      x-max-session=30

to any HTTP request sent to EtherCIS to reset the max number of sessions?

I assume the request must include a valid EtherCIS session Id?

Is it possible to interrogate EtherCIS to confirm the Max Sessions setting?

Thanks

Rob

**Comment by robtweed** [comment]
Christian - could you confirm my understanding - see my questions above

Rob

**Comment by chevalleyc** [comment]
When you first connect, with f.e. x-max-session=30 in your HTTP header, the response header contains:

```
Access-Control-Allow-Origin →*
Content-Language →en-US
Content-Length →127
Content-Type →application/json;charset=UTF-8
Date →Tue, 10 Oct 2017 02:24:16 GMT
Ehr-Session →CCH-1234
Server →Jetty(9.3.z-SNAPSHOT)
__rcvTimestampStr →2017-10-10 02:24:16.663Z
x-max-session →30
x-reconnect →false
x-session-name →/node/ehrserver/client/guest/-1
x-session-timeout →1800000
x-sessions-in-use →1
```
NB. session 'tweaking' can be done only at connect time, the parameters you pass are then session attributes valid for the session life time

**Comment by tony-shannon** [comment]
closing this @robtweed on advice from @chevalleyc  , please reopen if any related issues
