### ISSUE TITLE
Is DISTINCT ON is supported in AQL??

### ISSUE THREAD

**Issue by shafeef** [ethercis/ethercis#54]
Is DISTINCT ON is supported in AQL??

**Comment by chevalleyc** [comment]
DISTINCT is now supported (it is internally translated as DISTINCT ON).

**Comment by shafeef** [comment]
okay, but for the query, it returns result set duplicate ehrId

select distinct e/ehr_id/value as ehrId ,b_a/data[at0001]/items[at0.137]/items[at0.138]/value/value as Status from EHR e contains COMPOSITION a[openEHR-EHR-COMPOSITION.review.v1] contains (OBSERVATION b_a[openEHR-EHR-ADMIN_ENTRY.admission-extended.v1])

**Comment by shafeef** [comment]
Here is the response, you can see that same ehrid appears 2 times.

"resultSet": [
        {
            "Status": "Completed",
            "ehrId": "06231483-1102-4443-b406-f49969e65afe"
        },
        {
            "Status": "Checked",
            **"ehrId": "08ff6fc4-0493-4517-8814-193fbd76ca5c"**
        },
        {
            "Status": "Planned",
            **"ehrId": "08ff6fc4-0493-4517-8814-193fbd76ca5c"**
        },
        {
            "Status": "Completed",
            "ehrId": "0ff3e3c1-ebfd-4313-8920-17aa6ba94b4d"
        }

**Comment by chevalleyc** [comment]
Your query results as 'select distinct on (ehrId, Status). what you see is expected (you have different Status values)

**Comment by shafeef** [comment]
is there any option to get all compositions with unique ehrid's, means i need only latest composition entry

**Comment by chevalleyc** [comment]
Sorry I don't understand the question. Is this related to the DISTINCT ON issue or a separate question?

**Comment by shafeef** [comment]
about DISTINCT only

**Comment by chevalleyc** [comment]
Here is the actual SQL query from your AQL statement:

```
select distinct on (
  "ehrId", 
  "Status"
) 
  "alias_58744386"."ehrId", 
  "alias_58744386"."Status"
from (
  select 
    DISTINCT "ehr_join"."id" as "ehrId", 
    "ehr"."entry"."entry" #>> '{/composition[openEHR-EHR-COMPOSITION.review.v1 and name/value=''Review''],/content[openEHR-EHR-ADMIN_ENTRY.admission-extended.v1],0,/data[at0001],/items[at0.137],0,/items[at0.138],0,/value,value}' as "Status"
  from "ehr"."entry"
    join "ehr"."composition" as "composition_join"
    on "composition_join"."id" = "ehr"."entry"."composition_id"
    join "ehr"."ehr" as "ehr_join"
    on "ehr_join"."id" = "composition_join"."ehr_id"
  where "ehr"."entry"."template_id" = 'EHRN Episode details.v0'
) as "alias_58744386"
```
Perhaps if you use PGADMIN you can try to modify your query to get the result you expect. 

My take is that you could use a combination of LIMIT 1 and ORDER BY on context/start_time/value

**Comment by shafeef** [comment]
actually what i'm trying to fetch is, get latest compositions for each ehrid's under a template

**Comment by tony-shannon** [comment]
closing this @shafeef on advice from @chevalleyc , please reopen if any related issues
