### ISSUE TITLE
Where to place new libraries(jar) in my local etherCIS??

### ISSUE THREAD

**Issue by shafeef** [ethercis/ethercis#55]
Yesterday you have updated some jars, so Where to place new libraries(jar) in my local etherCIS??
check attachment
![libraries](https://user-images.githubusercontent.com/25655903/31264031-02e1311e-aa84-11e7-81e9-dcebef45c6b6.png)

**Comment by chevalleyc** [comment]
Don't use these libraries. The valid libraries are specified in your ecis-server script classpath.

**Comment by shafeef** [comment]
Okay thanks
