### ISSUE TITLE
AQL for multiple occurrence nodes

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#69]
Does Ethercis support aql on multi-occurrence nodes in compositions? If yes does it return all the values for the node or only the first one? 

If only the first one is returned, how do we query all the values? If all values arereturned, what is the aql syntax?

regards

**Comment by freshehr** [comment]
Hi Dileep,

I would expect all of the matching nodes to be returned. The AQL syntax should be identical.

Example from Think!Ehr. The last two results are from the same Entry




```
{
    "meta": {
        "href": "http://test.operon.systems/rest/v1/query/?aql=select%20a_a/data%5Bat0001%5D/items%5Bat0009,%20'Reaction%20details'%5D/items%5Bat0011%5D/value/value%20as%20Manifestation,%20a/uid/value%20as%20uid%20from%20EHR%20e%20contains%20COMPOSITION%20a%20contains%20EVALUATION%20a_a%5BopenEHR-EHR-EVALUATION.adverse_reaction_risk.v1%5D"
    },
    "aql": "select a_a/data[at0001]/items[at0009, 'Reaction details']/items[at0011]/value/value as Manifestation, a/uid/value as uid from EHR e contains COMPOSITION a contains EVALUATION a_a[openEHR-EHR-EVALUATION.adverse_reaction_risk.v1]",
    "executedAql": "select a_a/data[at0001]/items[at0009, 'Reaction details']/items[at0011]/value/value as Manifestation, a/uid/value as uid from EHR e contains COMPOSITION a contains EVALUATION a_a[openEHR-EHR-EVALUATION.adverse_reaction_risk.v1]",
    "resultSet": [
        {
            "uid": "9809c9bd-daca-4a6d-8a7f-e78fc947af8c::hcbox.oprn.ehrscape.com::1",
            "Manifestation": "eruption due to drug"
        },
        {
            "uid": "9809c9bd-daca-4a6d-8a7f-e78fc947af8c::hcbox.oprn.ehrscape.com::1",
            "Manifestation": "allergic angio-oedema due to ingested food"
        },
        {
            "uid": "91a65e46-e6f3-44a6-bfc8-a4fd6c45f815::hcbox.oprn.ehrscape.com::1",
            "Manifestation": "eruption due to drug"
        },
        {
            "uid": "6fe4570a-8e49-4a37-9905-26f4a57368b3::hcbox.oprn.ehrscape.com::1",
            "Manifestation": "sneezing"
        },
        {
            "uid": "f3c55ce4-9fcc-4bad-b772-4293242fd233::hcbox.oprn.ehrscape.com::1",
            "Manifestation": "sneezing"
        },
        {
            "uid": "f3c55ce4-9fcc-4bad-b772-4293242fd233::hcbox.oprn.ehrscape.com::1",
            "Manifestation": "conjunctivitis"
        }
    ]
}
```

Original composition for uid  "f3c55ce4-9fcc-4bad-b772-4293242fd233::hcbox.oprn.ehrscape.com::1",

```
{
  "ctx/composer_name": "Dr George Crooks",
  "ctx/health_care_facility|id": "999999-345",
  "ctx/health_care_facility|name": "Ripple junction DGH",
  "ctx/id_namespace": "NHS-UK",
  "ctx/id_scheme": "2.16.840.1.113883.2.1.4.3",
  "ctx/language": "en",
  "ctx/territory": "GB",
  "ctx/time": "2015-12-20T00:11:02.518+02:00",
   "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/causative_agent": "Grass pollen allergy",
  "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/reaction_details/manifestation:0": "sneezing",
   "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/reaction_details/manifestation:1": "conjunctivitis",
    "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/reaction_details/comment": "only in spring"
}
```
Not tested on EtherCis yet.

Ian

**Comment by freshehr** [comment]
Tested on EtherCis - not working correctly.

```
POST /rest/v1/composition?ehrId=4a704b79-72ec-4bf7-bf7b-b90c6225495a&amp;templateId=IDCR - Adverse Reaction List.v1&amp;committerName=Dr Franke&amp;format=FLAT HTTP/1.1
Host: 178.62.71.220:8080
Authorization: Basic Z3Vlc3Q6Z3Vlc3Q=
Ehr-Session: sessionId:127.0.0.1-guest-1509562858082-1598554451-60
Content-Type: application/json
Auth-Token: {{Auth-Token}}

{
  "ctx/composer_name": "Dr George Crooks",
  "ctx/health_care_facility|id": "999999-345",
  "ctx/health_care_facility|name": "Ripple junction DGH",
  "ctx/id_namespace": "NHS-UK",
  "ctx/id_scheme": "2.16.840.1.113883.2.1.4.3",
  "ctx/language": "en",
  "ctx/territory": "GB",
  "ctx/time": "2015-12-20T00:11:02.518+02:00",
   "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/causative_agent": "Grass pollen allergy",
  "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/reaction_details/manifestation:0": "terrble sneezing",
   "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/reaction_details/manifestation:1": "awful conjunctivitis",
    "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/reaction_details/comment": "only in spring"
}
```

AQL:

```
POST /rest/v1/query HTTP/1.1
Host: 178.62.71.220:8080
Content-Type: application/json
Authorization: Basic Z3Vlc3Q6Z3Vlc3Q=
Ehr-Session: sessionId:127.0.0.1-guest-1509562858082-1598554451-60
{
  "aql": "select a_a/data[at0001]/items[at0009]/items[at0011]/value/value as Manifestation, a/uid/value as uid from EHR e contains COMPOSITION a contains EVALUATION a_a[openEHR-EHR-EVALUATION.adverse_reaction_risk.v1]"
}
```

only the first manifestation is returned.

```
 {
            "uid": "b10d5ca1-1cfa-46c6-9dc2-e33890e758a3::vm01.ethercis.org::1",
            "Manifestation": "terrble sneezing"
        },
```

**Comment by chevalleyc** [comment]
This issue is set as a Long Term resolution in https://github.com/ethercis/ethercis/blob/master/ethercis-roadmap.md#long-term (querying arrays - or multiple occurrences as stated in this CR).

**Comment by freshehr** [comment]
@chevalleyc - I think this is worth bringing forward as there are quite a few archetypes/attributes where multiple occurrence is the norm, and may actually be fairly commonly used. There are some potential safety risks in data not being retrieved correctly.

**Comment by dileep-ehr** [comment]
Thanks Ian,

I also observed the same behaviour in ethercis and so raised the question
in openehr mailing list to understand the expected behaviour.

Regards

Dileep V S
Founder
HealtheLife Ventures LLP
+91 9632888113
103, Innovation Centre, IIIT, Electronics City, Bangalore 560100,
healthelife.in

On 02-Nov-2017 12:41 AM, "Ian McNicoll" <notifications@github.com> wrote:

Tested on EtherCis - not working correctly.

POST /rest/v1/composition?ehrId=4a704b79-72ec-4bf7-bf7b-b90c6225495a&amp;templateId=IDCR
- Adverse Reaction List.v1&amp;committerName=Dr Franke&amp;format=FLAT
HTTP/1.1
Host: 178.62.71.220:8080
Authorization: Basic Z3Vlc3Q6Z3Vlc3Q=
Ehr-Session: sessionId:127.0.0.1-guest-1509562858082-1598554451-60
Content-Type: application/json
Auth-Token: {{Auth-Token}}

{
  "ctx/composer_name": "Dr George Crooks",
  "ctx/health_care_facility|id": "999999-345",
  "ctx/health_care_facility|name": "Ripple junction DGH",
  "ctx/id_namespace": "NHS-UK",
  "ctx/id_scheme": "2.16.840.1.113883.2.1.4.3",
  "ctx/language": "en",
  "ctx/territory": "GB",
  "ctx/time": "2015-12-20T00:11:02.518+02:00",
   "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/causative_agent":
"Grass pollen allergy",
  "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/reaction_details/manifestation:0":
"terrble sneezing",
   "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/reaction_details/manifestation:1":
"awful conjunctivitis",
    "adverse_reaction_list/allergies_and_adverse_reactions/adverse_reaction_risk:0/reaction_details/comment":
"only in spring"
}

AQL:

POST /rest/v1/query HTTP/1.1
Host: 178.62.71.220:8080
Content-Type: application/json
Authorization: Basic Z3Vlc3Q6Z3Vlc3Q=
Ehr-Session: sessionId:127.0.0.1-guest-1509562858082-1598554451-60
{
  "aql": "select
a_a/data[at0001]/items[at0009]/items[at0011]/value/value as
Manifestation, a/uid/value as uid from EHR e contains COMPOSITION a
contains EVALUATION
a_a[openEHR-EHR-EVALUATION.adverse_reaction_risk.v1]"
}

only the first manifestation is returned.

 {
            "uid": "b10d5ca1-1cfa-46c6-9dc2-e33890e758a3::vm01.ethercis.org::1",
            "Manifestation": "terrble sneezing"
        },

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ethercis/ethercis/issues/69#issuecomment-341209003>,
or mute
the thread

**Comment by chevalleyc** [comment]
A work around is to get the raw json associated to the node:

<code>a_a/data[at0001]/items[at0009]</code>

But I agree, returning an array of occurrences (similar to what would be returned by a SQL query on a table or joined tables) is way more elegant and something we need. The change involve some significant work though.

**Comment by dileep-ehr** [comment]
Any thoughts on moving this item forward?

**Comment by chevalleyc** [comment]
included in v.1.2.0

**Comment by freshehr** [comment]
Hi Christian,

Nice - I'll test ASAP. This came up at a recent Spec meeting as it is behaviour that is shared by all of the current CDRs. My tech buddies tell me it is 'expected' :( 

How did you work around it? 

@serefarikan - will be interesting to get your take.

This is a really annoying 'feature' of AQL so progress is very welcome.

**Comment by chevalleyc** [comment]
I use the info from template/introspect. Whenever non-trivial occurrence (such as ../content) is declared, the AQL query is built recursively to deal with an array instead of a single item.
