### ISSUE TITLE
DataAccessException

### ISSUE THREAD

**Issue by rubal-jain** [ethercis/ethercis#70]
We are getting error during "running" vEhr. The error is:

-----------
11:52:25.623 [main] ERROR com.ethercis.servicemanager.service.ServiceManagerBase - The Service class or initializer 'com.ethercis.persistence.ResourceService' could not be loaded, exception:java.lang.NoClassDefFoundError: org/jooq/exception/DataAccessException
11:52:25.625 [main] DEBUG com.ethercis.servicemanager.runlevel.RunlevelManager - Successful startup to run level RUNNING [ 572 millis ]
11:52:25.625 [main] ERROR com.ethercis.vehr.VEhrGateServlet - ServiceManagerException errorCode=[resource.configuration.serviceFailed] serverSideException=true location=[RunlevelManager.startupServices] message=[#1.0.0 Can't load plugin 'ResourceService' : ServiceManagerException errorCode=[resource.configuration.serviceFailed] serverSideException=true location=[ServiceManagerBase] message=[#1.0.0 The Service class or initializer 'com.ethercis.persistence.ResourceService' could not be loaded, exception:java.lang.NoClassDefFoundError: org/jooq/exception/DataAccessException : ] [See URL http://.../doc/requirements/admin.errorcodes.listing.html#resource.configuration.serviceFailed]] [See URL http://.../doc/requirements/admin.errorcodes.listing.html#resource.configuration.serviceFailed]
11:52:25.625 [main] ERROR com.ethercis.vehr.VEhrGateServlet - Changing runlevel to 'RUNNING' failed, good bye
-----------

We have already commented out the DataAccessException in the ResourceService.java class in Service Implementation to manage access to resources. Done a clean and build multiple times and then tried running. Doesn't work.

**Comment by tony-shannon** [comment]
thanks, spoke to Christian on this.
The clue is here "exception:java.lang.NoClassDefFoundError: "
His view is that this most likely is a configuration issue in your local environment
To resolve will require knowing your dev set up and config and could take some hours to troubleshoot
I need to refer you to our project support ;
https://github.com/ethercis/ethercis#productproject-support
regards
Tony

**Comment by chevalleyc** [comment]
Closed due to lack of activity. Please reopen if needed. Thanks
