### ISSUE TITLE
AQL querying optimization

### ISSUE THREAD

**Issue by tony-shannon** [ethercis/ethercis#71]
- Refactor containment/path resolution (following Peter Macko note)
- Add filtering to containment query based on where clause if contains EHR and/or COMPOSITION attributes

**Comment by chevalleyc** [comment]
Another optimization step is about reducing the sql expression complexity (ex. querying on an embedded archetype which is contained by multiple template) for a given composition id. Needs to figure out the benefit since the query planner indicates processing time ~ 0.5 ms.

**Comment by chevalleyc** [comment]
Added to the roadmap a while ago.
