### ISSUE TITLE
API Explorer/swagger

### ISSUE THREAD

**Issue by dngferreira** [ethercis/ethercis#77]
Hi,
Nice job on the Ethercis project.
Are there any plans for the integration of swagger.io, or any other solution, to get an integrated API tester?

Thanks

**Comment by chevalleyc** [comment]
Hi Duarte, many thanks for the comment :)

We talk recurrently about swagger but, to be honest, don't have much time to dedicate to integrate it. We are always looking for contributor(s) to help moving forward ;) 

Cheers!

**Comment by freshehr** [comment]
Hi Duarte,

You might want to look at.

https://github.com/freshehr/postman-ehrscape

I much prefer working with Postman for openEHR API's. You will need to adapt the environment file to work with EtherCis but this is largely about changing the endpoint URL and login details.

Ian

**Comment by tony-shannon** [comment]
thanks @freshehr 
Is that (PostMan on EtherCIS) something you could do a .md file for this repo please?
Would be v helpful am sure
thanks
T

**Comment by chevalleyc** [comment]
Documented as per @freshehr answer.

**Comment by tony-shannon** [comment]
thanks
