### ISSUE TITLE
AQL fails on DV_CODED_TEXT object

### ISSUE THREAD

**Issue by freshehr** [ethercis/ethercis#82]
```
curl -X POST \
  http://178.62.71.220:8080/rest/v1/query \
  -H 'authorization: Basic Z3Vlc3Q6Z3Vlc3Q=' \
  -H 'content-type: application/json' \
  -H 'ehr-session: sessionId:127.0.0.1-guest-1512414477544--1964914083-1126' \
  -d '{
  "aql": "select e/ehr_id/value as ehrId, e/ehr_status/subject/external_ref/id/value as subjectId, e/ehr_status/subject/external_ref/namespace as subjectNamespace, a/uid/value as compositionId, b_a/data[at0001]/items[at0002]/value as Causative_agent from EHR e[ehr_id/value = '\''4a704b79-72ec-4bf7-bf7b-b90c6225495a'\''] contains COMPOSITION a[openEHR-EHR-COMPOSITION.adverse_reaction_list.v1] contains EVALUATION b_a[openEHR-EHR-EVALUATION.adverse_reaction_risk.v1] where a/name/value='\''Adverse reaction list'\''"
}'
```

result:
```
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
        <title>Error 500 </title>
    </head>
    <body>
        <h2>HTTP ERROR: 500</h2>
        <p>Problem accessing /rest/v1/query. Reason:

            <pre>    #1.0.0 Invocation exception to method:query:java.lang.IndexOutOfBoundsException: Index: 1, Size: 1</pre>
        </p>
        <hr />
        <a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.z-SNAPSHOT</a>
        <hr/>
    </body>
</html>
```

**Comment by chevalleyc** [comment]
locally tested. will push to the demo server after the we.

**Comment by chevalleyc** [comment]
moved to the test server. please check

**Comment by freshehr** [comment]
Tested - does not fail but not behaving as expected.

` b_a/data[at0001]/items[at0002]/value as Causative_agent` should return an object like

```
  "Causative_agent": {
                "@class": "DV_CODED_TEXT",
                "value": "4546",
                "defining_code": {
                    "@class": "CODE_PHRASE",
                    "terminology_id": {
                        "@class": "TERMINOLOGY_ID",
                        "value": "456654"
                    },
                    "code_string": "1239085"
                }
            },
```
All of the @class nodes are optional other than the root, since DV_TEXT can always be sub-classedot DV_CODED_TEXT.

We need to be able to handle objects so that multiple occurences e.g of 'Manifestations' can  be easily handled - if we use scalars, the AQL generates a new row for each occurence, which is correct but very difficult to reconstruct.

The handling of multiple objects was working in labs.

**Comment by chevalleyc** [comment]
I don't mean to be pedantic, but returning a JSON structure is not an AQL requirement unless I miss something. Perhaps, the conversion from scalar list to json should be the responsibility of the middleware (f.e. QWED)?

**Comment by freshehr** [comment]
Apologies - my error - wrong AQL. Tested and confirmed working!  Still need to test multiple occurences.

**Comment by freshehr** [comment]
Returning an object is most definitely part of AQL requirement. JSON is not the only way but it does need to be supported.

**Comment by chevalleyc** [comment]
I would rather wait this is an actual specification then :-). Thanks!

**Comment by freshehr** [comment]
I am happy with the current outcome - closing this issue
