### ISSUE TITLE
Creating composition with ratio type

### ISSUE THREAD

**Issue by linto17** [ethercis/ethercis#83]
Hi, I am getting the following error when committing a composition with ratio type.

#1.0.0 Invocation exception to method:create:java.lang.IllegalArgumentException: Unhandled data type:at0003, List

    "encounter/anthropometry:0/waist-hip_ratio:0/waist-hip_ratio|numerator": 1,
    "encounter/anthropometry:0/waist-hip_ratio:0/waist-hip_ratio|denominator": 1,
    "encounter/anthropometry:0/waist-hip_ratio:0/waist-hip_ratio": 1,

**Comment by chevalleyc** [comment]
Could you please post the complete composition json body and associated template? Thanks

**Comment by linto17** [comment]
Attached OPT and JSON example.

[OPT&example.zip](https://github.com/ethercis/ethercis/files/1558048/OPT.example.zip)

**Comment by chevalleyc** [comment]
Could you send me an actual POST body (not an example) you try to commit? Tx

**Comment by linto17** [comment]
{
  "ctx/language":"en",
  "encounter/_uid": "e781b1ac-6b35-4490-8147-e108723da1f9::example.ethercis.com::1",
  "encounter/language|code": "en",
  "encounter/language|terminology": "ISO_639-1",
  "encounter/territory|code": "GB",
  "encounter/territory|terminology": "ISO_3166-1",
  "encounter/context/_health_care_facility|id": "123456-123",
  "encounter/context/_health_care_facility|id_scheme": "ETHERCIS-SCHEME",
  "encounter/context/_health_care_facility|id_namespace": "DEMOGRAPHIC",
  "encounter/context/_health_care_facility|name": "FACILITY",
  "encounter/context/start_time": "2017-12-11T15:21:56.874+05:30",
  "encounter/context/setting|code": "238",
  "encounter/context/setting|value": "Other Care",
  "encounter/context/setting|terminology": "openehr",
  "encounter/anthropometry:0/height_length:0/any_event:0/height_length|magnitude": 1.0,
  "encounter/anthropometry:0/height_length:0/any_event:0/height_length|unit": "cm",
  
  "encounter/anthropometry:0/body_weight:0/any_event:0/weight|magnitude": 2.0,
  "encounter/anthropometry:0/body_weight:0/any_event:0/weight|unit": "kg",
  
  "encounter/anthropometry:0/arm_circumference:0/any_event:0/left_arm_circumference|magnitude": 3.0,
  "encounter/anthropometry:0/arm_circumference:0/any_event:0/left_arm_circumference|unit": "cm",
  
  "encounter/anthropometry:0/arm_circumference:0/any_event:0/right_arm_circumference|magnitude": 4.0,
  "encounter/anthropometry:0/arm_circumference:0/any_event:0/right_arm_circumference|unit": "cm",
  
  "encounter/anthropometry:0/chest_circumference:0/any_event:0/chest_circumference|magnitude": 5.0,
  "encounter/anthropometry:0/chest_circumference:0/any_event:0/chest_circumference|unit": "cm",
  
  "encounter/anthropometry:0/waist_circumference:0/any_event:0/waist_circumference|magnitude": 6.0,
  "encounter/anthropometry:0/waist_circumference:0/any_event:0/waist_circumference|unit": "cm",
  
  "encounter/anthropometry:0/hip_circumference:0/any_event:0/hip_circumference|magnitude": 7.0,
  "encounter/anthropometry:0/hip_circumference:0/any_event:0/hip_circumference|unit": "cm",
  
  "encounter/anthropometry:0/thigh_circumference:0/any_event:0/left_thigh_circumference|magnitude": 8.0,
  "encounter/anthropometry:0/thigh_circumference:0/any_event:0/left_thigh_circumference|unit": "cm",
  
  "encounter/anthropometry:0/thigh_circumference:0/any_event:0/right_thigh_circumference|magnitude": 9.0,
  "encounter/anthropometry:0/thigh_circumference:0/any_event:0/right_thigh_circumference|unit": "cm",
  
  "encounter/anthropometry:0/waist-hip_ratio:0/waist-hip_ratio|numerator": 1.0,
  "encounter/anthropometry:0/waist-hip_ratio:0/waist-hip_ratio|denominator": 1.0,
  "encounter/anthropometry:0/waist-hip_ratio:0/waist-hip_ratio": 1.0,
  
  "encounter/composer|id": "1234-5678",
  "encounter/composer|id_scheme": "ETHERCIS-TEST",
  "encounter/composer|id_namespace": "DEMOGRAPHIC",
  "encounter/composer|name": "Composer",
  "encounter/composer/_identifier:0": "1234-5678",
  "encounter/composer/_identifier:0|issuer": "ETHERCIS",
  "encounter/composer/_identifier:0|assigner": "dummy",
  "encounter/composer/_identifier:0|type": "dummy"
}

**Comment by chevalleyc** [comment]
did you have a chance to update your library and check it out?

**Comment by linto17** [comment]
Thanks, The new libraries are updated in Release?
