### ISSUE TITLE
Unclear which DDL is the correct one

### ISSUE THREAD

**Issue by ralphvanetten** [ethercis/ethercis#9]
In the sources there are a lot of DDL floating around. In our fork I picked one which looked the most complete (`jooq-pg/main/resources/ddls/pgsql_ehr.ddl`) and added that one to flyway (which we are using to manage database schemas in our fork)

I'm not sure if the one I picked is the proper one though.

**Comment by chevalleyc** [comment]
see [PR#5](https://github.com/ethercis/ehrservice/pull/5/commits)
